// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use crate::use_cases::common::rust_code_generator::{GenerationOps, GenerationReadOps};
use crate::use_cases::generate_rust_prompt_uc::{
    GenerateRustPromptUnitOfWorkFactoryTrait, GenerateRustPromptUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
use common::entities::{
    Dto, DtoField, Entity, Feature, Field, File, Global, Relationship, Root, System, UseCase,
    UserInterface, Workspace,
};
use common::event::EventHub;
use common::types::EntityId;
use std::cell::RefCell;
use std::sync::Arc;
// Unit of work for GenerateRustPrompt

pub struct GenerateRustPromptUnitOfWork {
    context: DbContext,
    transaction: RefCell<Option<Transaction>>,
    #[allow(dead_code)]
    event_hub: Arc<EventHub>,
}

impl GenerateRustPromptUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        GenerateRustPromptUnitOfWork {
            context: db_context.clone(),
            transaction: RefCell::new(None),
            event_hub: event_hub.clone(),
        }
    }
}

impl QueryUnitOfWork for GenerateRustPromptUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationshipRO, GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/generate_rust_prompt_uc.rs
//
#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Root", action = "GetAllRO")]
#[macros::uow_action(entity = "System", action = "GetRO")]
#[macros::uow_action(entity = "Workspace", action = "GetRO")]
#[macros::uow_action(entity = "Workspace", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "UserInterface", action = "GetRO")]
#[macros::uow_action(entity = "File", action = "GetRO")]
#[macros::uow_action(entity = "Global", action = "GetRO")]
#[macros::uow_action(entity = "Feature", action = "GetRO")]
#[macros::uow_action(entity = "Feature", action = "GetMultiRO")]
#[macros::uow_action(entity = "UseCase", action = "GetRO")]
#[macros::uow_action(entity = "UseCase", action = "GetMultiRO")]
#[macros::uow_action(entity = "Dto", action = "GetRO")]
#[macros::uow_action(entity = "DtoField", action = "GetMultiRO")]
#[macros::uow_action(entity = "Entity", action = "GetRO")]
#[macros::uow_action(entity = "Entity", action = "GetMultiRO")]
#[macros::uow_action(entity = "Field", action = "GetMultiRO")]
#[macros::uow_action(entity = "Relationship", action = "GetMultiRO")]
impl GenerationReadOps for GenerateRustPromptUnitOfWork {}

impl GenerateRustPromptUnitOfWorkTrait for GenerateRustPromptUnitOfWork {}

#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Root", action = "GetAllRO")]
#[macros::uow_action(entity = "System", action = "GetRO")]
#[macros::uow_action(entity = "Workspace", action = "GetRO")]
#[macros::uow_action(entity = "Workspace", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "UserInterface", action = "GetRO")]
#[macros::uow_action(entity = "File", action = "GetRO")]
#[macros::uow_action(entity = "Global", action = "GetRO")]
#[macros::uow_action(entity = "Feature", action = "GetRO")]
#[macros::uow_action(entity = "Feature", action = "GetMultiRO")]
#[macros::uow_action(entity = "UseCase", action = "GetRO")]
#[macros::uow_action(entity = "UseCase", action = "GetMultiRO")]
#[macros::uow_action(entity = "Dto", action = "GetRO")]
#[macros::uow_action(entity = "DtoField", action = "GetMultiRO")]
#[macros::uow_action(entity = "Entity", action = "GetRO")]
#[macros::uow_action(entity = "Entity", action = "GetMultiRO")]
#[macros::uow_action(entity = "Field", action = "GetMultiRO")]
#[macros::uow_action(entity = "Relationship", action = "GetMultiRO")]
impl GenerationOps for GenerateRustPromptUnitOfWork {}

pub struct GenerateRustPromptUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl GenerateRustPromptUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        GenerateRustPromptUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl GenerateRustPromptUnitOfWorkFactoryTrait for GenerateRustPromptUnitOfWorkFactory {
    fn create(&self) -> Box<dyn GenerateRustPromptUnitOfWorkTrait> {
        Box::new(GenerateRustPromptUnitOfWork::new(
            &self.context,
            &self.event_hub,
        ))
    }
}
