// Generated by Qleany v1.12.0 from frontend_flat_event.tera

//! Flat event representation for simplified consumer-side matching.
//!
//! Collapses the nested `Origin → DirectAccessEntity → EntityEvent` hierarchy
//! into a single-level `FlatEventKind` enum. Every consumer can subscribe to
//! all events once and match on a flat enum instead of reconstructing nested
//! `Origin` values.

use common::event::{
    AllEvent, CppQtFileGenerationEvent, DirectAccessEntity, EntityEvent, Event,
    FileGenerationSharedStepsEvent, HandlingAppLifecycleEvent, HandlingManifestEvent,
    LongOperationEvent, Origin, RustFileGenerationEvent, UndoRedoEvent,
};
use common::types::EntityId;

/// Flat representation of all event origins.
///
/// Collapses `Origin → DirectAccessEntity → EntityEvent` into a single level.
/// Generated from the manifest: adding an entity or feature adds variants,
/// and the compiler flags every consumer that needs updating.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum FlatEventKind {
    // Per-entity events
    RootCreated,
    RootUpdated,
    RootRemoved,
    WorkspaceCreated,
    WorkspaceUpdated,
    WorkspaceRemoved,
    SystemCreated,
    SystemUpdated,
    SystemRemoved,
    EntityCreated,
    EntityUpdated,
    EntityRemoved,
    FieldCreated,
    FieldUpdated,
    FieldRemoved,
    FeatureCreated,
    FeatureUpdated,
    FeatureRemoved,
    FileCreated,
    FileUpdated,
    FileRemoved,
    UseCaseCreated,
    UseCaseUpdated,
    UseCaseRemoved,
    DtoCreated,
    DtoUpdated,
    DtoRemoved,
    DtoFieldCreated,
    DtoFieldUpdated,
    DtoFieldRemoved,
    GlobalCreated,
    GlobalUpdated,
    GlobalRemoved,
    RelationshipCreated,
    RelationshipUpdated,
    RelationshipRemoved,
    UserInterfaceCreated,
    UserInterfaceUpdated,
    UserInterfaceRemoved,

    // Per-feature use case events
    HandlingAppLifecycleInitializeApp,
    HandlingAppLifecycleCleanUpBeforeExit,

    HandlingManifestLoad,
    HandlingManifestSave,
    HandlingManifestCreate,
    HandlingManifestClose,
    HandlingManifestExportToMermaid,
    HandlingManifestCheck,

    RustFileGenerationFillRustFiles,
    RustFileGenerationFillCodeInRustFiles,
    RustFileGenerationGenerateRustCode,
    RustFileGenerationGenerateRustFiles,
    RustFileGenerationGenerateRustPrompt,

    CppQtFileGenerationFillCppQtFiles,
    CppQtFileGenerationGenerateCppQtCode,
    CppQtFileGenerationGenerateCppQtFiles,
    CppQtFileGenerationFillCodeInCppQtFiles,
    CppQtFileGenerationGenerateCppQtPrompt,

    FileGenerationSharedStepsFillStatusInFiles,
    FileGenerationSharedStepsGetFileDiff,

    // Undo/redo
    UndoPerformed,
    RedoPerformed,
    UndoStackChanged,
    CompositeBegin,
    CompositeEnd,
    CompositeCancelled,

    // Long operations
    LongOperationStarted,
    LongOperationProgress,
    LongOperationCompleted,
    LongOperationFailed,
    LongOperationCancelled,

    // System
    Reset,
}

/// An event with a flattened kind, ready for consumer-side matching.
#[derive(Debug, Clone)]
pub struct FlatEvent {
    pub kind: FlatEventKind,
    pub ids: Vec<EntityId>,
    pub data: Option<String>,
}

impl From<Event> for FlatEvent {
    fn from(event: Event) -> Self {
        let kind = match &event.origin {
            Origin::DirectAccess(da) => match da {
                DirectAccessEntity::All(AllEvent::Reset) => FlatEventKind::Reset,

                DirectAccessEntity::Root(EntityEvent::Created) => FlatEventKind::RootCreated,
                DirectAccessEntity::Root(EntityEvent::Updated) => FlatEventKind::RootUpdated,
                DirectAccessEntity::Root(EntityEvent::Removed) => FlatEventKind::RootRemoved,
                DirectAccessEntity::Workspace(EntityEvent::Created) => {
                    FlatEventKind::WorkspaceCreated
                }
                DirectAccessEntity::Workspace(EntityEvent::Updated) => {
                    FlatEventKind::WorkspaceUpdated
                }
                DirectAccessEntity::Workspace(EntityEvent::Removed) => {
                    FlatEventKind::WorkspaceRemoved
                }
                DirectAccessEntity::System(EntityEvent::Created) => FlatEventKind::SystemCreated,
                DirectAccessEntity::System(EntityEvent::Updated) => FlatEventKind::SystemUpdated,
                DirectAccessEntity::System(EntityEvent::Removed) => FlatEventKind::SystemRemoved,
                DirectAccessEntity::Entity(EntityEvent::Created) => FlatEventKind::EntityCreated,
                DirectAccessEntity::Entity(EntityEvent::Updated) => FlatEventKind::EntityUpdated,
                DirectAccessEntity::Entity(EntityEvent::Removed) => FlatEventKind::EntityRemoved,
                DirectAccessEntity::Field(EntityEvent::Created) => FlatEventKind::FieldCreated,
                DirectAccessEntity::Field(EntityEvent::Updated) => FlatEventKind::FieldUpdated,
                DirectAccessEntity::Field(EntityEvent::Removed) => FlatEventKind::FieldRemoved,
                DirectAccessEntity::Feature(EntityEvent::Created) => FlatEventKind::FeatureCreated,
                DirectAccessEntity::Feature(EntityEvent::Updated) => FlatEventKind::FeatureUpdated,
                DirectAccessEntity::Feature(EntityEvent::Removed) => FlatEventKind::FeatureRemoved,
                DirectAccessEntity::File(EntityEvent::Created) => FlatEventKind::FileCreated,
                DirectAccessEntity::File(EntityEvent::Updated) => FlatEventKind::FileUpdated,
                DirectAccessEntity::File(EntityEvent::Removed) => FlatEventKind::FileRemoved,
                DirectAccessEntity::UseCase(EntityEvent::Created) => FlatEventKind::UseCaseCreated,
                DirectAccessEntity::UseCase(EntityEvent::Updated) => FlatEventKind::UseCaseUpdated,
                DirectAccessEntity::UseCase(EntityEvent::Removed) => FlatEventKind::UseCaseRemoved,
                DirectAccessEntity::Dto(EntityEvent::Created) => FlatEventKind::DtoCreated,
                DirectAccessEntity::Dto(EntityEvent::Updated) => FlatEventKind::DtoUpdated,
                DirectAccessEntity::Dto(EntityEvent::Removed) => FlatEventKind::DtoRemoved,
                DirectAccessEntity::DtoField(EntityEvent::Created) => {
                    FlatEventKind::DtoFieldCreated
                }
                DirectAccessEntity::DtoField(EntityEvent::Updated) => {
                    FlatEventKind::DtoFieldUpdated
                }
                DirectAccessEntity::DtoField(EntityEvent::Removed) => {
                    FlatEventKind::DtoFieldRemoved
                }
                DirectAccessEntity::Global(EntityEvent::Created) => FlatEventKind::GlobalCreated,
                DirectAccessEntity::Global(EntityEvent::Updated) => FlatEventKind::GlobalUpdated,
                DirectAccessEntity::Global(EntityEvent::Removed) => FlatEventKind::GlobalRemoved,
                DirectAccessEntity::Relationship(EntityEvent::Created) => {
                    FlatEventKind::RelationshipCreated
                }
                DirectAccessEntity::Relationship(EntityEvent::Updated) => {
                    FlatEventKind::RelationshipUpdated
                }
                DirectAccessEntity::Relationship(EntityEvent::Removed) => {
                    FlatEventKind::RelationshipRemoved
                }
                DirectAccessEntity::UserInterface(EntityEvent::Created) => {
                    FlatEventKind::UserInterfaceCreated
                }
                DirectAccessEntity::UserInterface(EntityEvent::Updated) => {
                    FlatEventKind::UserInterfaceUpdated
                }
                DirectAccessEntity::UserInterface(EntityEvent::Removed) => {
                    FlatEventKind::UserInterfaceRemoved
                }
            },

            Origin::HandlingAppLifecycle(fe) => match fe {
                HandlingAppLifecycleEvent::InitializeApp => {
                    FlatEventKind::HandlingAppLifecycleInitializeApp
                }
                HandlingAppLifecycleEvent::CleanUpBeforeExit => {
                    FlatEventKind::HandlingAppLifecycleCleanUpBeforeExit
                }
            },
            Origin::HandlingManifest(fe) => match fe {
                HandlingManifestEvent::Load => FlatEventKind::HandlingManifestLoad,
                HandlingManifestEvent::Save => FlatEventKind::HandlingManifestSave,
                HandlingManifestEvent::Create => FlatEventKind::HandlingManifestCreate,
                HandlingManifestEvent::Close => FlatEventKind::HandlingManifestClose,
                HandlingManifestEvent::ExportToMermaid => {
                    FlatEventKind::HandlingManifestExportToMermaid
                }
                HandlingManifestEvent::Check => FlatEventKind::HandlingManifestCheck,
            },
            Origin::RustFileGeneration(fe) => match fe {
                RustFileGenerationEvent::FillRustFiles => {
                    FlatEventKind::RustFileGenerationFillRustFiles
                }
                RustFileGenerationEvent::FillCodeInRustFiles => {
                    FlatEventKind::RustFileGenerationFillCodeInRustFiles
                }
                RustFileGenerationEvent::GenerateRustCode => {
                    FlatEventKind::RustFileGenerationGenerateRustCode
                }
                RustFileGenerationEvent::GenerateRustFiles => {
                    FlatEventKind::RustFileGenerationGenerateRustFiles
                }
                RustFileGenerationEvent::GenerateRustPrompt => {
                    FlatEventKind::RustFileGenerationGenerateRustPrompt
                }
            },
            Origin::CppQtFileGeneration(fe) => match fe {
                CppQtFileGenerationEvent::FillCppQtFiles => {
                    FlatEventKind::CppQtFileGenerationFillCppQtFiles
                }
                CppQtFileGenerationEvent::GenerateCppQtCode => {
                    FlatEventKind::CppQtFileGenerationGenerateCppQtCode
                }
                CppQtFileGenerationEvent::GenerateCppQtFiles => {
                    FlatEventKind::CppQtFileGenerationGenerateCppQtFiles
                }
                CppQtFileGenerationEvent::FillCodeInCppQtFiles => {
                    FlatEventKind::CppQtFileGenerationFillCodeInCppQtFiles
                }
                CppQtFileGenerationEvent::GenerateCppQtPrompt => {
                    FlatEventKind::CppQtFileGenerationGenerateCppQtPrompt
                }
            },
            Origin::FileGenerationSharedSteps(fe) => match fe {
                FileGenerationSharedStepsEvent::FillStatusInFiles => {
                    FlatEventKind::FileGenerationSharedStepsFillStatusInFiles
                }
                FileGenerationSharedStepsEvent::GetFileDiff => {
                    FlatEventKind::FileGenerationSharedStepsGetFileDiff
                }
            },
            Origin::UndoRedo(ur) => match ur {
                UndoRedoEvent::Undone => FlatEventKind::UndoPerformed,
                UndoRedoEvent::Redone => FlatEventKind::RedoPerformed,
                UndoRedoEvent::StackChanged => FlatEventKind::UndoStackChanged,
                UndoRedoEvent::BeginComposite => FlatEventKind::CompositeBegin,
                UndoRedoEvent::EndComposite => FlatEventKind::CompositeEnd,
                UndoRedoEvent::CancelComposite => FlatEventKind::CompositeCancelled,
            },
            Origin::LongOperation(lo) => match lo {
                LongOperationEvent::Started => FlatEventKind::LongOperationStarted,
                LongOperationEvent::Progress => FlatEventKind::LongOperationProgress,
                LongOperationEvent::Completed => FlatEventKind::LongOperationCompleted,
                LongOperationEvent::Failed => FlatEventKind::LongOperationFailed,
                LongOperationEvent::Cancelled => FlatEventKind::LongOperationCancelled,
            },
        };
        FlatEvent {
            kind,
            ids: event.ids,
            data: event.data,
        }
    }
}

/// Returns `true` if this event kind represents an entity mutation (created, updated, or removed).
pub fn is_mutation(kind: &FlatEventKind) -> bool {
    use FlatEventKind::*;
    matches!(
        kind,
        RootCreated
            | RootUpdated
            | RootRemoved
            | WorkspaceCreated
            | WorkspaceUpdated
            | WorkspaceRemoved
            | SystemCreated
            | SystemUpdated
            | SystemRemoved
            | EntityCreated
            | EntityUpdated
            | EntityRemoved
            | FieldCreated
            | FieldUpdated
            | FieldRemoved
            | FeatureCreated
            | FeatureUpdated
            | FeatureRemoved
            | FileCreated
            | FileUpdated
            | FileRemoved
            | UseCaseCreated
            | UseCaseUpdated
            | UseCaseRemoved
            | DtoCreated
            | DtoUpdated
            | DtoRemoved
            | DtoFieldCreated
            | DtoFieldUpdated
            | DtoFieldRemoved
            | GlobalCreated
            | GlobalUpdated
            | GlobalRemoved
            | RelationshipCreated
            | RelationshipUpdated
            | RelationshipRemoved
            | UserInterfaceCreated
            | UserInterfaceUpdated
            | UserInterfaceRemoved
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_entity_event_converts_to_flat() {
        let event = Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        };
        let flat: FlatEvent = event.into();
        assert_eq!(flat.kind, FlatEventKind::Reset);
    }

    #[test]
    fn test_undo_redo_converts_to_flat() {
        let event = Event {
            origin: Origin::UndoRedo(UndoRedoEvent::Undone),
            ids: vec![],
            data: None,
        };
        let flat: FlatEvent = event.into();
        assert_eq!(flat.kind, FlatEventKind::UndoPerformed);
    }

    #[test]
    fn test_is_mutation() {
        assert!(is_mutation(&FlatEventKind::RootCreated));
        assert!(is_mutation(&FlatEventKind::RootUpdated));
        assert!(is_mutation(&FlatEventKind::RootRemoved));

        assert!(is_mutation(&FlatEventKind::WorkspaceCreated));
        assert!(is_mutation(&FlatEventKind::WorkspaceUpdated));
        assert!(is_mutation(&FlatEventKind::WorkspaceRemoved));

        assert!(is_mutation(&FlatEventKind::SystemCreated));
        assert!(is_mutation(&FlatEventKind::SystemUpdated));
        assert!(is_mutation(&FlatEventKind::SystemRemoved));

        assert!(is_mutation(&FlatEventKind::EntityCreated));
        assert!(is_mutation(&FlatEventKind::EntityUpdated));
        assert!(is_mutation(&FlatEventKind::EntityRemoved));

        assert!(is_mutation(&FlatEventKind::FieldCreated));
        assert!(is_mutation(&FlatEventKind::FieldUpdated));
        assert!(is_mutation(&FlatEventKind::FieldRemoved));

        assert!(is_mutation(&FlatEventKind::FeatureCreated));
        assert!(is_mutation(&FlatEventKind::FeatureUpdated));
        assert!(is_mutation(&FlatEventKind::FeatureRemoved));

        assert!(is_mutation(&FlatEventKind::FileCreated));
        assert!(is_mutation(&FlatEventKind::FileUpdated));
        assert!(is_mutation(&FlatEventKind::FileRemoved));

        assert!(is_mutation(&FlatEventKind::UseCaseCreated));
        assert!(is_mutation(&FlatEventKind::UseCaseUpdated));
        assert!(is_mutation(&FlatEventKind::UseCaseRemoved));

        assert!(is_mutation(&FlatEventKind::DtoCreated));
        assert!(is_mutation(&FlatEventKind::DtoUpdated));
        assert!(is_mutation(&FlatEventKind::DtoRemoved));

        assert!(is_mutation(&FlatEventKind::DtoFieldCreated));
        assert!(is_mutation(&FlatEventKind::DtoFieldUpdated));
        assert!(is_mutation(&FlatEventKind::DtoFieldRemoved));

        assert!(is_mutation(&FlatEventKind::GlobalCreated));
        assert!(is_mutation(&FlatEventKind::GlobalUpdated));
        assert!(is_mutation(&FlatEventKind::GlobalRemoved));

        assert!(is_mutation(&FlatEventKind::RelationshipCreated));
        assert!(is_mutation(&FlatEventKind::RelationshipUpdated));
        assert!(is_mutation(&FlatEventKind::RelationshipRemoved));

        assert!(is_mutation(&FlatEventKind::UserInterfaceCreated));
        assert!(is_mutation(&FlatEventKind::UserInterfaceUpdated));
        assert!(is_mutation(&FlatEventKind::UserInterfaceRemoved));

        assert!(!is_mutation(&FlatEventKind::Reset));
        assert!(!is_mutation(&FlatEventKind::UndoPerformed));
        assert!(!is_mutation(&FlatEventKind::LongOperationStarted));
    }
}
