// Generated by Qleany v1.12.0 from frontend_lib.tera

//! Frontend crate - public API for the generated backend.
//!
//! This crate re-exports everything a UI consumer needs:
//! `AppContext`, command wrappers, event client, and DTOs.
//!
//! DTOs are accessible via structured paths:
//!   - `frontend::{entity}::dtos::{Entity}Dto`
//!   - `frontend::{feature}::dtos::{UseCaseDto}`

pub mod app_context;
pub mod commands;
pub mod event_hub_client;
pub mod flat_event;

// Core type re-exports
pub use anyhow::{Context, Result};
pub use app_context::AppContext;
pub use common::event::{Event, Origin};
pub use common::long_operation::OperationProgress;
pub use common::types::EntityId;
pub use event_hub_client::EventHubClient;
pub use flat_event::{FlatEvent, FlatEventKind};

// Entity modules (DTOs via frontend::{entity}::dtos::{Entity}Dto)
pub use direct_access::dto;
pub use direct_access::dto_field;
pub use direct_access::entity;
pub use direct_access::feature;
pub use direct_access::field;
pub use direct_access::file;
pub use direct_access::global;
pub use direct_access::relationship;
pub use direct_access::root;
pub use direct_access::system;
pub use direct_access::use_case;
pub use direct_access::user_interface;
pub use direct_access::workspace;

// Feature modules (DTOs via frontend::{feature}::dtos::{Dto})
pub use cpp_qt_file_generation;
pub use file_generation_shared_steps;
pub use handling_app_lifecycle;
pub use handling_manifest;
pub use rust_file_generation;

// Full backend crates available for advanced use
pub use common;
pub use direct_access;
