// Generated by Qleany v0.0.1 from feature_use_case_uow.tera

use crate::use_cases::create_uc::{CreateUnitOfWorkFactoryTrait, CreateUnitOfWorkTrait};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
use common::event::EventHub;
use std::cell::RefCell;
use std::sync::Arc;

// Unit of work for Create

pub struct CreateUnitOfWork {
    context: DbContext,
    #[allow(dead_code)]
    event_hub: Arc<EventHub>,
    transaction: RefCell<Option<Transaction>>,
}

impl CreateUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        CreateUnitOfWork {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for CreateUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

//TODO: adapt entities and actions to real use :
// GetRO, GetMultiRO, GetRelationshipRO, GetRelationshipsFromRightIdsRO
//
// You have here a read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/create_uc.rs
//
impl CreateUnitOfWorkTrait for CreateUnitOfWork {}

pub struct CreateUnitOfWorkFactory {
    context: DbContext,
    #[allow(dead_code)]
    event_hub: Arc<EventHub>,
}

impl CreateUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        CreateUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl CreateUnitOfWorkFactoryTrait for CreateUnitOfWorkFactory {
    fn create(&self) -> Box<dyn CreateUnitOfWorkTrait> {
        Box::new(CreateUnitOfWork::new(&self.context, &self.event_hub))
    }
}
