// Generated by Qleany. Edit at your own risk! Be careful when regenerating this file
// as changes will be lost.

use crate::use_cases::export_to_mermaid_uc::{
    ExportToMermaidUnitOfWorkFactoryTrait, ExportToMermaidUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
use common::entities::{
    Dto, DtoField, Entity, Feature, Field, Global, Relationship, Root, UseCase, UserInterface,
    Workspace,
};
use common::event::EventHub;
use common::types::EntityId;
use std::cell::RefCell;
use std::sync::Arc;

// Unit of work for ExportToMermaid

pub struct ExportToMermaidUnitOfWork {
    context: DbContext,
    #[allow(dead_code)]
    event_hub: Arc<EventHub>,
    transaction: RefCell<Option<Transaction>>,
}

impl ExportToMermaidUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        ExportToMermaidUnitOfWork {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
            transaction: RefCell::new(None),
        }
    }
}

impl QueryUnitOfWork for ExportToMermaidUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        self.transaction
            .replace(Some(Transaction::begin_read_transaction(&self.context)?));
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}

//TODO: adapt entities and actions to real use : Create, CreateMulti, Get, GetMulti, Update, UpdateMulti, Delete,
//DeleteMulti, GetRO, GetMultiRO, GetRelationship, GetRelationshipRO, GetRelationshipsFromRightIds,
//GetRelationshipsFromRightIdsRO, SetRelationship, SetRelationshipMulti
//
// You have here a read-only unit of work.
//
// RO means Read Only, so *RO actions should be used here.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/export_to_mermaid_uc.rs
//

#[macros::uow_action(entity = "Dto", action = "GetRO")]
#[macros::uow_action(entity = "Dto", action = "GetMultiRO")]
#[macros::uow_action(entity = "DtoField", action = "GetRO")]
#[macros::uow_action(entity = "DtoField", action = "GetMultiRO")]
#[macros::uow_action(entity = "Global", action = "GetRO")]
#[macros::uow_action(entity = "Global", action = "GetMultiRO")]
#[macros::uow_action(entity = "Relationship", action = "GetRO")]
#[macros::uow_action(entity = "Relationship", action = "GetMultiRO")]
#[macros::uow_action(entity = "UserInterface", action = "GetRO")]
#[macros::uow_action(entity = "UserInterface", action = "GetMultiRO")]
#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetAllRO")]
#[macros::uow_action(entity = "Workspace", action = "GetRO")]
#[macros::uow_action(entity = "Workspace", action = "GetMultiRO")]
#[macros::uow_action(entity = "Entity", action = "GetRO")]
#[macros::uow_action(entity = "Entity", action = "GetMultiRO")]
#[macros::uow_action(entity = "Field", action = "GetRO")]
#[macros::uow_action(entity = "Field", action = "GetMultiRO")]
#[macros::uow_action(entity = "Feature", action = "GetRO")]
#[macros::uow_action(entity = "Feature", action = "GetMultiRO")]
#[macros::uow_action(entity = "UseCase", action = "GetRO")]
#[macros::uow_action(entity = "UseCase", action = "GetMultiRO")]
impl ExportToMermaidUnitOfWorkTrait for ExportToMermaidUnitOfWork {}

pub struct ExportToMermaidUnitOfWorkFactory {
    context: DbContext,
    #[allow(dead_code)]
    event_hub: Arc<EventHub>,
}

impl ExportToMermaidUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        ExportToMermaidUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl ExportToMermaidUnitOfWorkFactoryTrait for ExportToMermaidUnitOfWorkFactory {
    fn create(&self) -> Box<dyn ExportToMermaidUnitOfWorkTrait> {
        Box::new(ExportToMermaidUnitOfWork::new(
            &self.context,
            &self.event_hub,
        ))
    }
}
