// Generated by Qleany v1.11.0 from direct_access_lib.tera

// Panic hygiene. Every generated unit-of-work method returns `Result`, so the
// templates propagate a missing transaction with `?` instead of panicking on it,
// and every store lock goes through `read_or_recover`/`write_or_recover`. That
// leaves this crate at zero panic paths outside tests — this lint keeps it there,
// including across regeneration, which is why it lives in the template and not in
// the consuming project's `Cargo.toml`.
//
// `not(test)`, because "outside tests" is meant literally: the generated
// controller tests unwrap freely, as test code should, and a crate-wide warn
// flagged every one of them under `--all-targets`.
#![cfg_attr(
    not(test),
    warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)
)]

// This file defines the direct_access crate public API.

// Project entities (auto-listed)

// Root
pub mod root;

// Workspace
pub mod workspace;

// System
pub mod system;

// Entity
pub mod entity;

// Field
pub mod field;

// Feature
pub mod feature;

// File
pub mod file;

// UseCase
pub mod use_case;

// Dto
pub mod dto;

// DtoField
pub mod dto_field;

// Global
pub mod global;

// Relationship
pub mod relationship;

// UserInterface
pub mod user_interface;

// Re-exports for all project entities

pub use root::dtos::*;
pub use root::root_controller;

pub use workspace::dtos::*;
pub use workspace::workspace_controller;

pub use system::dtos::*;
pub use system::system_controller;

pub use entity::dtos::*;
pub use entity::entity_controller;

pub use field::dtos::*;
pub use field::field_controller;

pub use feature::dtos::*;
pub use feature::feature_controller;

pub use file::dtos::*;
pub use file::file_controller;

pub use use_case::dtos::*;
pub use use_case::use_case_controller;

pub use dto::dto_controller;
pub use dto::dtos::*;

pub use dto_field::dto_field_controller;
pub use dto_field::dtos::*;

pub use global::dtos::*;
pub use global::global_controller;

pub use relationship::dtos::*;
pub use relationship::relationship_controller;

pub use user_interface::dtos::*;
pub use user_interface::user_interface_controller;
