// Generated by Qleany v1.12.0 from teksilo_single_entity.tera//! `SingleUserInterface` -- a reactive handle over one `UserInterface`.

#[cfg(not(feature = "mocks"))]
mod imp {
    use std::cell::{Cell, RefCell};
    use std::rc::Rc;

    use teksilo::core::signal::ObserverHandle;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::commands::user_interface_commands;
    use frontend::common::event::{DirectAccessEntity, EntityEvent, Event, Origin};
    use frontend::direct_access::{UpdateUserInterfaceDto, UserInterfaceDto};

    use crate::singles::LoadingStatus;

    struct Inner {
        id: Cell<Option<EntityId>>,
        dto: Signal<Option<UserInterfaceDto>>,
        created_at: Signal<chrono::DateTime<chrono::Utc>>,
        updated_at: Signal<chrono::DateTime<chrono::Utc>>,
        rust_cli: Signal<bool>,
        rust_slint: Signal<bool>,
        rust_teksilo: Signal<bool>,
        cpp_qt_qtwidgets: Signal<bool>,
        cpp_qt_qtquick: Signal<bool>,
        rust_ios: Signal<bool>,
        rust_android: Signal<bool>,
        loading_status: Signal<LoadingStatus>,
        error_message: Signal<String>,
        dirty: Signal<bool>,
        /// Set while `refresh` / `clear` write the field signals, so a
        /// programmatic load does not trip the dirty flag.
        is_refreshing: Rc<Cell<bool>>,
        /// Held for the life of the handle; dropping one would stop that field
        /// from marking the handle dirty.
        _dirty_observers: RefCell<Vec<ObserverHandle>>,
        ctx: Rc<AppContext>,
    }

    #[derive(Clone)]
    pub struct SingleUserInterface {
        inner: Rc<Inner>,
    }

    #[allow(dead_code)] // full reactive surface; consumers wire up incrementally
    impl SingleUserInterface {
        pub fn new(ctx: Rc<AppContext>) -> Self {
            let inner = Rc::new(Inner {
                id: Cell::new(None),
                dto: Signal::new(None),
                created_at: Signal::new(Default::default()),
                updated_at: Signal::new(Default::default()),
                rust_cli: Signal::new(Default::default()),
                rust_slint: Signal::new(Default::default()),
                rust_teksilo: Signal::new(Default::default()),
                cpp_qt_qtwidgets: Signal::new(Default::default()),
                cpp_qt_qtquick: Signal::new(Default::default()),
                rust_ios: Signal::new(Default::default()),
                rust_android: Signal::new(Default::default()),
                loading_status: Signal::new(LoadingStatus::Unloaded),
                error_message: Signal::new(String::new()),
                dirty: Signal::new(false),
                is_refreshing: Rc::new(Cell::new(false)),
                _dirty_observers: RefCell::new(Vec::new()),
                ctx,
            });

            // A widget bound straight to a field signal -- `TextInput::new(s.title())`
            // -- writes it without passing through `set_title`, so dirtiness is
            // tracked here rather than in the setters. These closures capture the
            // two shared handles and never `Rc<Inner>`, so there is no cycle.
            {
                let mut observers = inner._dirty_observers.borrow_mut();
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.rust_cli.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.rust_slint.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.rust_teksilo.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.cpp_qt_qtwidgets.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.cpp_qt_qtquick.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.rust_ios.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.rust_android.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                let _ = &mut observers;
            }

            Self { inner }
        }

        pub fn set_id(&self, id: Option<EntityId>) {
            self.inner.id.set(id);
            match id {
                Some(_) => self.refresh(),
                None => self.clear(),
            }
        }

        pub fn id(&self) -> Option<EntityId> {
            self.inner.id.get()
        }

        /// Stay live. Call from a long-lived widget's `build`, on every build:
        /// a `BuildContext` subscription is scoped to the current build and
        /// dropped on the next, so a one-shot "already wired" guard would leave
        /// the handle deaf while still reporting itself wired.
        pub fn wire(&self, ctx: &mut BuildContext) {
            {
                let me = self.clone();
                ctx.subscribe_event(
                    Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Updated)),
                    move |event: &Event| {
                        if me.is_mine(event) {
                            me.refresh();
                        }
                    },
                );
            }
            {
                let me = self.clone();
                ctx.subscribe_event(
                    Origin::DirectAccess(DirectAccessEntity::UserInterface(EntityEvent::Removed)),
                    move |event: &Event| {
                        if me.is_mine(event) {
                            me.inner.id.set(None);
                            me.clear();
                        }
                    },
                );
            }
            // Catch up: a handle pointed at an id before it was wired, or
            // re-wired after a rebuild, must not wait for the next edit.
            if self.inner.id.get().is_some() {
                self.refresh();
            }
        }

        fn is_mine(&self, event: &Event) -> bool {
            self.inner
                .id
                .get()
                .map(|id| event.ids.contains(&id))
                .unwrap_or(false)
        }

        pub fn dto(&self) -> Option<UserInterfaceDto> {
            self.inner.dto.get()
        }

        pub fn dto_signal(&self) -> Signal<Option<UserInterfaceDto>> {
            self.inner.dto.clone()
        }

        pub fn loading_status(&self) -> Signal<LoadingStatus> {
            self.inner.loading_status.clone()
        }

        pub fn error_message(&self) -> Signal<String> {
            self.inner.error_message.clone()
        }

        pub fn dirty(&self) -> Signal<bool> {
            self.inner.dirty.clone()
        }

        pub fn created_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.created_at.clone()
        }

        pub fn updated_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.updated_at.clone()
        }

        pub fn rust_cli(&self) -> Signal<bool> {
            self.inner.rust_cli.clone()
        }

        pub fn set_rust_cli(&self, value: bool) {
            self.inner.rust_cli.set(value);
        }

        pub fn rust_slint(&self) -> Signal<bool> {
            self.inner.rust_slint.clone()
        }

        pub fn set_rust_slint(&self, value: bool) {
            self.inner.rust_slint.set(value);
        }

        pub fn rust_teksilo(&self) -> Signal<bool> {
            self.inner.rust_teksilo.clone()
        }

        pub fn set_rust_teksilo(&self, value: bool) {
            self.inner.rust_teksilo.set(value);
        }

        pub fn cpp_qt_qtwidgets(&self) -> Signal<bool> {
            self.inner.cpp_qt_qtwidgets.clone()
        }

        pub fn set_cpp_qt_qtwidgets(&self, value: bool) {
            self.inner.cpp_qt_qtwidgets.set(value);
        }

        pub fn cpp_qt_qtquick(&self) -> Signal<bool> {
            self.inner.cpp_qt_qtquick.clone()
        }

        pub fn set_cpp_qt_qtquick(&self, value: bool) {
            self.inner.cpp_qt_qtquick.set(value);
        }

        pub fn rust_ios(&self) -> Signal<bool> {
            self.inner.rust_ios.clone()
        }

        pub fn set_rust_ios(&self, value: bool) {
            self.inner.rust_ios.set(value);
        }

        pub fn rust_android(&self) -> Signal<bool> {
            self.inner.rust_android.clone()
        }

        pub fn set_rust_android(&self, value: bool) {
            self.inner.rust_android.set(value);
        }

        /// Write the field signals back. No-op when clean, unset, or never
        /// loaded -- that last guard stops a handle that failed to load from
        /// stamping `Default::default()` over a live row.
        ///
        /// `stack_id` is accepted whether or not this entity is undoable, so a
        /// caller never has to branch on the manifest.
        pub fn save(&self, stack_id: Option<u64>) {
            let Some(id) = self.inner.id.get() else {
                return;
            };
            if !self.inner.dirty.get() {
                return;
            }
            if self.inner.loading_status.get() != LoadingStatus::Loaded {
                return;
            }
            self.inner.loading_status.set(LoadingStatus::Loading);

            // Read-modify-write: the stored entity is the source of truth for
            // everything this handle does not own.
            let existing = match user_interface_commands::get_user_interface(&self.inner.ctx, &id) {
                Ok(Some(entity)) => entity,
                Ok(None) => return self.fail("UserInterface not found"),
                Err(e) => return self.fail(&e.to_string()),
            };

            let dto = UpdateUserInterfaceDto {
                id,
                // Carried verbatim: re-deriving it resets the creation time on
                // every edit.
                created_at: existing.created_at,
                updated_at: chrono::Utc::now(),
                rust_cli: self.inner.rust_cli.get(),
                rust_slint: self.inner.rust_slint.get(),
                rust_teksilo: self.inner.rust_teksilo.get(),
                cpp_qt_qtwidgets: self.inner.cpp_qt_qtwidgets.get(),
                cpp_qt_qtquick: self.inner.cpp_qt_qtquick.get(),
                rust_ios: self.inner.rust_ios.get(),
                rust_android: self.inner.rust_android.get(),
            };

            match user_interface_commands::update_user_interface(&self.inner.ctx, stack_id, &dto) {
                Ok(updated) => {
                    self.inner.dto.set_if_changed(Some(updated));
                    self.inner.dirty.set(false);
                    self.inner.loading_status.set(LoadingStatus::Loaded);
                }
                Err(e) => self.fail(&e.to_string()),
            }
        }

        /// Re-read from the backend.
        pub fn refresh(&self) {
            let Some(id) = self.inner.id.get() else {
                return;
            };
            self.inner.loading_status.set(LoadingStatus::Loading);
            match user_interface_commands::get_user_interface(&self.inner.ctx, &id) {
                Ok(Some(dto)) => {
                    self.inner.is_refreshing.set(true);
                    // `set_if_changed` throughout: this runs on every `Updated`,
                    // so editing one field must not wake the observers of all
                    // the others.
                    self.inner.created_at.set_if_changed(dto.created_at);
                    self.inner.updated_at.set_if_changed(dto.updated_at);
                    self.inner.rust_cli.set_if_changed(dto.rust_cli);
                    self.inner.rust_slint.set_if_changed(dto.rust_slint);
                    self.inner.rust_teksilo.set_if_changed(dto.rust_teksilo);
                    self.inner
                        .cpp_qt_qtwidgets
                        .set_if_changed(dto.cpp_qt_qtwidgets);
                    self.inner.cpp_qt_qtquick.set_if_changed(dto.cpp_qt_qtquick);
                    self.inner.rust_ios.set_if_changed(dto.rust_ios);
                    self.inner.rust_android.set_if_changed(dto.rust_android);
                    self.inner.dto.set_if_changed(Some(dto));
                    self.inner.is_refreshing.set(false);
                    self.inner.dirty.set(false);
                    self.inner.error_message.set(String::new());
                    self.inner.loading_status.set(LoadingStatus::Loaded);
                }
                Ok(None) => self.clear(),
                Err(e) => self.fail(&e.to_string()),
            }
        }

        /// Reset every field signal and go `Unloaded`.
        pub fn clear(&self) {
            self.inner.is_refreshing.set(true);
            self.inner.created_at.set_if_changed(Default::default());
            self.inner.updated_at.set_if_changed(Default::default());
            self.inner.rust_cli.set_if_changed(Default::default());
            self.inner.rust_slint.set_if_changed(Default::default());
            self.inner.rust_teksilo.set_if_changed(Default::default());
            self.inner
                .cpp_qt_qtwidgets
                .set_if_changed(Default::default());
            self.inner.cpp_qt_qtquick.set_if_changed(Default::default());
            self.inner.rust_ios.set_if_changed(Default::default());
            self.inner.rust_android.set_if_changed(Default::default());
            self.inner.dto.set_if_changed(None);
            self.inner.is_refreshing.set(false);
            self.inner.dirty.set(false);
            self.inner.error_message.set(String::new());
            self.inner.loading_status.set(LoadingStatus::Unloaded);
        }

        fn fail(&self, message: &str) {
            self.inner.error_message.set(message.to_string());
            self.inner.loading_status.set(LoadingStatus::Error);
        }
    }
}

#[cfg(feature = "mocks")]
mod imp {
    use std::cell::Cell;
    use std::rc::Rc;

    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::direct_access::UserInterfaceDto;

    use crate::singles::LoadingStatus;

    struct Inner {
        id: Cell<Option<EntityId>>,
        dto: Signal<Option<UserInterfaceDto>>,
        created_at: Signal<chrono::DateTime<chrono::Utc>>,
        updated_at: Signal<chrono::DateTime<chrono::Utc>>,
        rust_cli: Signal<bool>,
        rust_slint: Signal<bool>,
        rust_teksilo: Signal<bool>,
        cpp_qt_qtwidgets: Signal<bool>,
        cpp_qt_qtquick: Signal<bool>,
        rust_ios: Signal<bool>,
        rust_android: Signal<bool>,
        loading_status: Signal<LoadingStatus>,
        error_message: Signal<String>,
        dirty: Signal<bool>,
    }

    #[derive(Clone)]
    pub struct SingleUserInterface {
        inner: Rc<Inner>,
    }

    /// Deterministic, never random: this is called on demand, so a fresh value
    /// per call would make the same row change identity between refreshes and
    /// anything keyed on it would treat every refresh as a new row.
    ///
    /// Only plain non-list `String` fields get a fabricated value; everything
    /// else stays at its type default, which is the one choice that compiles
    /// for an arbitrary entity.
    fn mock_dto(id: EntityId) -> UserInterfaceDto {
        UserInterfaceDto {
            id,
            ..Default::default()
        }
    }

    #[allow(dead_code)] // identical surface to the real arm; some unused here
    impl SingleUserInterface {
        pub fn new(_ctx: Rc<AppContext>) -> Self {
            let dto = mock_dto(1);
            Self {
                inner: Rc::new(Inner {
                    id: Cell::new(Some(1)),
                    created_at: Signal::new(dto.created_at),
                    updated_at: Signal::new(dto.updated_at),
                    rust_cli: Signal::new(dto.rust_cli),
                    rust_slint: Signal::new(dto.rust_slint),
                    rust_teksilo: Signal::new(dto.rust_teksilo),
                    cpp_qt_qtwidgets: Signal::new(dto.cpp_qt_qtwidgets),
                    cpp_qt_qtquick: Signal::new(dto.cpp_qt_qtquick),
                    rust_ios: Signal::new(dto.rust_ios),
                    rust_android: Signal::new(dto.rust_android),
                    dto: Signal::new(Some(dto)),
                    loading_status: Signal::new(LoadingStatus::Loaded),
                    error_message: Signal::new(String::new()),
                    dirty: Signal::new(false),
                }),
            }
        }

        pub fn set_id(&self, id: Option<EntityId>) {
            self.inner.id.set(id);
            match id {
                Some(id) => {
                    let dto = mock_dto(id);
                    self.inner.created_at.set_if_changed(dto.created_at);
                    self.inner.updated_at.set_if_changed(dto.updated_at);
                    self.inner.rust_cli.set_if_changed(dto.rust_cli);
                    self.inner.rust_slint.set_if_changed(dto.rust_slint);
                    self.inner.rust_teksilo.set_if_changed(dto.rust_teksilo);
                    self.inner
                        .cpp_qt_qtwidgets
                        .set_if_changed(dto.cpp_qt_qtwidgets);
                    self.inner.cpp_qt_qtquick.set_if_changed(dto.cpp_qt_qtquick);
                    self.inner.rust_ios.set_if_changed(dto.rust_ios);
                    self.inner.rust_android.set_if_changed(dto.rust_android);
                    self.inner.dto.set_if_changed(Some(dto));
                    self.inner.loading_status.set(LoadingStatus::Loaded);
                }
                None => {
                    self.inner.dto.set_if_changed(None);
                    self.inner.loading_status.set(LoadingStatus::Unloaded);
                }
            }
        }

        pub fn id(&self) -> Option<EntityId> {
            self.inner.id.get()
        }

        /// No-op under mocks, and deliberately so: a mocks build registers no
        /// event source, and `BuildContext::subscribe_event` panics without one.
        pub fn wire(&self, _ctx: &mut BuildContext) {}

        pub fn dto(&self) -> Option<UserInterfaceDto> {
            self.inner.dto.get()
        }

        pub fn dto_signal(&self) -> Signal<Option<UserInterfaceDto>> {
            self.inner.dto.clone()
        }

        pub fn loading_status(&self) -> Signal<LoadingStatus> {
            self.inner.loading_status.clone()
        }

        pub fn error_message(&self) -> Signal<String> {
            self.inner.error_message.clone()
        }

        pub fn dirty(&self) -> Signal<bool> {
            self.inner.dirty.clone()
        }

        pub fn created_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.created_at.clone()
        }

        pub fn updated_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.updated_at.clone()
        }

        pub fn rust_cli(&self) -> Signal<bool> {
            self.inner.rust_cli.clone()
        }

        pub fn set_rust_cli(&self, value: bool) {
            self.inner.rust_cli.set(value);
        }

        pub fn rust_slint(&self) -> Signal<bool> {
            self.inner.rust_slint.clone()
        }

        pub fn set_rust_slint(&self, value: bool) {
            self.inner.rust_slint.set(value);
        }

        pub fn rust_teksilo(&self) -> Signal<bool> {
            self.inner.rust_teksilo.clone()
        }

        pub fn set_rust_teksilo(&self, value: bool) {
            self.inner.rust_teksilo.set(value);
        }

        pub fn cpp_qt_qtwidgets(&self) -> Signal<bool> {
            self.inner.cpp_qt_qtwidgets.clone()
        }

        pub fn set_cpp_qt_qtwidgets(&self, value: bool) {
            self.inner.cpp_qt_qtwidgets.set(value);
        }

        pub fn cpp_qt_qtquick(&self) -> Signal<bool> {
            self.inner.cpp_qt_qtquick.clone()
        }

        pub fn set_cpp_qt_qtquick(&self, value: bool) {
            self.inner.cpp_qt_qtquick.set(value);
        }

        pub fn rust_ios(&self) -> Signal<bool> {
            self.inner.rust_ios.clone()
        }

        pub fn set_rust_ios(&self, value: bool) {
            self.inner.rust_ios.set(value);
        }

        pub fn rust_android(&self) -> Signal<bool> {
            self.inner.rust_android.clone()
        }

        pub fn set_rust_android(&self, value: bool) {
            self.inner.rust_android.set(value);
        }

        pub fn save(&self, _stack_id: Option<u64>) {
            self.inner.dirty.set(false);
        }

        pub fn refresh(&self) {}

        pub fn clear(&self) {
            self.inner.dto.set_if_changed(None);
            self.inner.loading_status.set(LoadingStatus::Unloaded);
        }
    }
}

pub use imp::SingleUserInterface;
