// Generated by Qleany v1.12.0 from teksilo_single_entity.tera//! `SingleGlobal` -- a reactive handle over one `Global`.

#[cfg(not(feature = "mocks"))]
mod imp {
    use std::cell::{Cell, RefCell};
    use std::rc::Rc;

    use teksilo::core::signal::ObserverHandle;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::commands::global_commands;
    use frontend::common::event::{DirectAccessEntity, EntityEvent, Event, Origin};
    use frontend::direct_access::{GlobalDto, UpdateGlobalDto};

    use crate::singles::LoadingStatus;

    struct Inner {
        id: Cell<Option<EntityId>>,
        dto: Signal<Option<GlobalDto>>,
        created_at: Signal<chrono::DateTime<chrono::Utc>>,
        updated_at: Signal<chrono::DateTime<chrono::Utc>>,
        language: Signal<String>,
        application_name: Signal<String>,
        organisation_name: Signal<String>,
        organisation_domain: Signal<String>,
        prefix_path: Signal<String>,
        loading_status: Signal<LoadingStatus>,
        error_message: Signal<String>,
        dirty: Signal<bool>,
        /// Set while `refresh` / `clear` write the field signals, so a
        /// programmatic load does not trip the dirty flag.
        is_refreshing: Rc<Cell<bool>>,
        /// Held for the life of the handle; dropping one would stop that field
        /// from marking the handle dirty.
        _dirty_observers: RefCell<Vec<ObserverHandle>>,
        ctx: Rc<AppContext>,
    }

    #[derive(Clone)]
    pub struct SingleGlobal {
        inner: Rc<Inner>,
    }

    #[allow(dead_code)] // full reactive surface; consumers wire up incrementally
    impl SingleGlobal {
        pub fn new(ctx: Rc<AppContext>) -> Self {
            let inner = Rc::new(Inner {
                id: Cell::new(None),
                dto: Signal::new(None),
                created_at: Signal::new(Default::default()),
                updated_at: Signal::new(Default::default()),
                language: Signal::new(Default::default()),
                application_name: Signal::new(Default::default()),
                organisation_name: Signal::new(Default::default()),
                organisation_domain: Signal::new(Default::default()),
                prefix_path: Signal::new(Default::default()),
                loading_status: Signal::new(LoadingStatus::Unloaded),
                error_message: Signal::new(String::new()),
                dirty: Signal::new(false),
                is_refreshing: Rc::new(Cell::new(false)),
                _dirty_observers: RefCell::new(Vec::new()),
                ctx,
            });

            // A widget bound straight to a field signal -- `TextInput::new(s.title())`
            // -- writes it without passing through `set_title`, so dirtiness is
            // tracked here rather than in the setters. These closures capture the
            // two shared handles and never `Rc<Inner>`, so there is no cycle.
            {
                let mut observers = inner._dirty_observers.borrow_mut();
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.language.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.application_name.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.organisation_name.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.organisation_domain.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                {
                    let dirty = inner.dirty.clone();
                    let refreshing = inner.is_refreshing.clone();
                    observers.push(inner.prefix_path.observe(move |_| {
                        if !refreshing.get() {
                            dirty.set(true);
                        }
                    }));
                }
                let _ = &mut observers;
            }

            Self { inner }
        }

        pub fn set_id(&self, id: Option<EntityId>) {
            self.inner.id.set(id);
            match id {
                Some(_) => self.refresh(),
                None => self.clear(),
            }
        }

        pub fn id(&self) -> Option<EntityId> {
            self.inner.id.get()
        }

        /// Stay live. Call from a long-lived widget's `build`, on every build:
        /// a `BuildContext` subscription is scoped to the current build and
        /// dropped on the next, so a one-shot "already wired" guard would leave
        /// the handle deaf while still reporting itself wired.
        pub fn wire(&self, ctx: &mut BuildContext) {
            {
                let me = self.clone();
                ctx.subscribe_event(
                    Origin::DirectAccess(DirectAccessEntity::Global(EntityEvent::Updated)),
                    move |event: &Event| {
                        if me.is_mine(event) {
                            me.refresh();
                        }
                    },
                );
            }
            {
                let me = self.clone();
                ctx.subscribe_event(
                    Origin::DirectAccess(DirectAccessEntity::Global(EntityEvent::Removed)),
                    move |event: &Event| {
                        if me.is_mine(event) {
                            me.inner.id.set(None);
                            me.clear();
                        }
                    },
                );
            }
            // Catch up: a handle pointed at an id before it was wired, or
            // re-wired after a rebuild, must not wait for the next edit.
            if self.inner.id.get().is_some() {
                self.refresh();
            }
        }

        fn is_mine(&self, event: &Event) -> bool {
            self.inner
                .id
                .get()
                .map(|id| event.ids.contains(&id))
                .unwrap_or(false)
        }

        pub fn dto(&self) -> Option<GlobalDto> {
            self.inner.dto.get()
        }

        pub fn dto_signal(&self) -> Signal<Option<GlobalDto>> {
            self.inner.dto.clone()
        }

        pub fn loading_status(&self) -> Signal<LoadingStatus> {
            self.inner.loading_status.clone()
        }

        pub fn error_message(&self) -> Signal<String> {
            self.inner.error_message.clone()
        }

        pub fn dirty(&self) -> Signal<bool> {
            self.inner.dirty.clone()
        }

        pub fn created_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.created_at.clone()
        }

        pub fn updated_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.updated_at.clone()
        }

        pub fn language(&self) -> Signal<String> {
            self.inner.language.clone()
        }

        pub fn set_language(&self, value: String) {
            self.inner.language.set(value);
        }

        pub fn application_name(&self) -> Signal<String> {
            self.inner.application_name.clone()
        }

        pub fn set_application_name(&self, value: String) {
            self.inner.application_name.set(value);
        }

        pub fn organisation_name(&self) -> Signal<String> {
            self.inner.organisation_name.clone()
        }

        pub fn set_organisation_name(&self, value: String) {
            self.inner.organisation_name.set(value);
        }

        pub fn organisation_domain(&self) -> Signal<String> {
            self.inner.organisation_domain.clone()
        }

        pub fn set_organisation_domain(&self, value: String) {
            self.inner.organisation_domain.set(value);
        }

        pub fn prefix_path(&self) -> Signal<String> {
            self.inner.prefix_path.clone()
        }

        pub fn set_prefix_path(&self, value: String) {
            self.inner.prefix_path.set(value);
        }

        /// Write the field signals back. No-op when clean, unset, or never
        /// loaded -- that last guard stops a handle that failed to load from
        /// stamping `Default::default()` over a live row.
        ///
        /// `stack_id` is accepted whether or not this entity is undoable, so a
        /// caller never has to branch on the manifest.
        pub fn save(&self, stack_id: Option<u64>) {
            let Some(id) = self.inner.id.get() else {
                return;
            };
            if !self.inner.dirty.get() {
                return;
            }
            if self.inner.loading_status.get() != LoadingStatus::Loaded {
                return;
            }
            self.inner.loading_status.set(LoadingStatus::Loading);

            // Read-modify-write: the stored entity is the source of truth for
            // everything this handle does not own.
            let existing = match global_commands::get_global(&self.inner.ctx, &id) {
                Ok(Some(entity)) => entity,
                Ok(None) => return self.fail("Global not found"),
                Err(e) => return self.fail(&e.to_string()),
            };

            let dto = UpdateGlobalDto {
                id,
                // Carried verbatim: re-deriving it resets the creation time on
                // every edit.
                created_at: existing.created_at,
                updated_at: chrono::Utc::now(),
                language: self.inner.language.get(),
                application_name: self.inner.application_name.get(),
                organisation_name: self.inner.organisation_name.get(),
                organisation_domain: self.inner.organisation_domain.get(),
                prefix_path: self.inner.prefix_path.get(),
            };

            match global_commands::update_global(&self.inner.ctx, stack_id, &dto) {
                Ok(updated) => {
                    self.inner.dto.set_if_changed(Some(updated));
                    self.inner.dirty.set(false);
                    self.inner.loading_status.set(LoadingStatus::Loaded);
                }
                Err(e) => self.fail(&e.to_string()),
            }
        }

        /// Re-read from the backend.
        pub fn refresh(&self) {
            let Some(id) = self.inner.id.get() else {
                return;
            };
            self.inner.loading_status.set(LoadingStatus::Loading);
            match global_commands::get_global(&self.inner.ctx, &id) {
                Ok(Some(dto)) => {
                    self.inner.is_refreshing.set(true);
                    // `set_if_changed` throughout: this runs on every `Updated`,
                    // so editing one field must not wake the observers of all
                    // the others.
                    self.inner.created_at.set_if_changed(dto.created_at);
                    self.inner.updated_at.set_if_changed(dto.updated_at);
                    self.inner.language.set_if_changed(dto.language.clone());
                    self.inner
                        .application_name
                        .set_if_changed(dto.application_name.clone());
                    self.inner
                        .organisation_name
                        .set_if_changed(dto.organisation_name.clone());
                    self.inner
                        .organisation_domain
                        .set_if_changed(dto.organisation_domain.clone());
                    self.inner
                        .prefix_path
                        .set_if_changed(dto.prefix_path.clone());
                    self.inner.dto.set_if_changed(Some(dto));
                    self.inner.is_refreshing.set(false);
                    self.inner.dirty.set(false);
                    self.inner.error_message.set(String::new());
                    self.inner.loading_status.set(LoadingStatus::Loaded);
                }
                Ok(None) => self.clear(),
                Err(e) => self.fail(&e.to_string()),
            }
        }

        /// Reset every field signal and go `Unloaded`.
        pub fn clear(&self) {
            self.inner.is_refreshing.set(true);
            self.inner.created_at.set_if_changed(Default::default());
            self.inner.updated_at.set_if_changed(Default::default());
            self.inner.language.set_if_changed(Default::default());
            self.inner
                .application_name
                .set_if_changed(Default::default());
            self.inner
                .organisation_name
                .set_if_changed(Default::default());
            self.inner
                .organisation_domain
                .set_if_changed(Default::default());
            self.inner.prefix_path.set_if_changed(Default::default());
            self.inner.dto.set_if_changed(None);
            self.inner.is_refreshing.set(false);
            self.inner.dirty.set(false);
            self.inner.error_message.set(String::new());
            self.inner.loading_status.set(LoadingStatus::Unloaded);
        }

        fn fail(&self, message: &str) {
            self.inner.error_message.set(message.to_string());
            self.inner.loading_status.set(LoadingStatus::Error);
        }
    }
}

#[cfg(feature = "mocks")]
mod imp {
    use std::cell::Cell;
    use std::rc::Rc;

    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::direct_access::GlobalDto;

    use crate::singles::LoadingStatus;

    struct Inner {
        id: Cell<Option<EntityId>>,
        dto: Signal<Option<GlobalDto>>,
        created_at: Signal<chrono::DateTime<chrono::Utc>>,
        updated_at: Signal<chrono::DateTime<chrono::Utc>>,
        language: Signal<String>,
        application_name: Signal<String>,
        organisation_name: Signal<String>,
        organisation_domain: Signal<String>,
        prefix_path: Signal<String>,
        loading_status: Signal<LoadingStatus>,
        error_message: Signal<String>,
        dirty: Signal<bool>,
    }

    #[derive(Clone)]
    pub struct SingleGlobal {
        inner: Rc<Inner>,
    }

    /// Deterministic, never random: this is called on demand, so a fresh value
    /// per call would make the same row change identity between refreshes and
    /// anything keyed on it would treat every refresh as a new row.
    ///
    /// Only plain non-list `String` fields get a fabricated value; everything
    /// else stays at its type default, which is the one choice that compiles
    /// for an arbitrary entity.
    fn mock_dto(id: EntityId) -> GlobalDto {
        GlobalDto {
            id,
            language: format!("Mock Global {id}"),
            application_name: format!("Mock Global {id}"),
            organisation_name: format!("Mock Global {id}"),
            organisation_domain: format!("Mock Global {id}"),
            prefix_path: format!("Mock Global {id}"),
            ..Default::default()
        }
    }

    #[allow(dead_code)] // identical surface to the real arm; some unused here
    impl SingleGlobal {
        pub fn new(_ctx: Rc<AppContext>) -> Self {
            let dto = mock_dto(1);
            Self {
                inner: Rc::new(Inner {
                    id: Cell::new(Some(1)),
                    created_at: Signal::new(dto.created_at),
                    updated_at: Signal::new(dto.updated_at),
                    language: Signal::new(dto.language.clone()),
                    application_name: Signal::new(dto.application_name.clone()),
                    organisation_name: Signal::new(dto.organisation_name.clone()),
                    organisation_domain: Signal::new(dto.organisation_domain.clone()),
                    prefix_path: Signal::new(dto.prefix_path.clone()),
                    dto: Signal::new(Some(dto)),
                    loading_status: Signal::new(LoadingStatus::Loaded),
                    error_message: Signal::new(String::new()),
                    dirty: Signal::new(false),
                }),
            }
        }

        pub fn set_id(&self, id: Option<EntityId>) {
            self.inner.id.set(id);
            match id {
                Some(id) => {
                    let dto = mock_dto(id);
                    self.inner.created_at.set_if_changed(dto.created_at);
                    self.inner.updated_at.set_if_changed(dto.updated_at);
                    self.inner.language.set_if_changed(dto.language.clone());
                    self.inner
                        .application_name
                        .set_if_changed(dto.application_name.clone());
                    self.inner
                        .organisation_name
                        .set_if_changed(dto.organisation_name.clone());
                    self.inner
                        .organisation_domain
                        .set_if_changed(dto.organisation_domain.clone());
                    self.inner
                        .prefix_path
                        .set_if_changed(dto.prefix_path.clone());
                    self.inner.dto.set_if_changed(Some(dto));
                    self.inner.loading_status.set(LoadingStatus::Loaded);
                }
                None => {
                    self.inner.dto.set_if_changed(None);
                    self.inner.loading_status.set(LoadingStatus::Unloaded);
                }
            }
        }

        pub fn id(&self) -> Option<EntityId> {
            self.inner.id.get()
        }

        /// No-op under mocks, and deliberately so: a mocks build registers no
        /// event source, and `BuildContext::subscribe_event` panics without one.
        pub fn wire(&self, _ctx: &mut BuildContext) {}

        pub fn dto(&self) -> Option<GlobalDto> {
            self.inner.dto.get()
        }

        pub fn dto_signal(&self) -> Signal<Option<GlobalDto>> {
            self.inner.dto.clone()
        }

        pub fn loading_status(&self) -> Signal<LoadingStatus> {
            self.inner.loading_status.clone()
        }

        pub fn error_message(&self) -> Signal<String> {
            self.inner.error_message.clone()
        }

        pub fn dirty(&self) -> Signal<bool> {
            self.inner.dirty.clone()
        }

        pub fn created_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.created_at.clone()
        }

        pub fn updated_at(&self) -> Signal<chrono::DateTime<chrono::Utc>> {
            self.inner.updated_at.clone()
        }

        pub fn language(&self) -> Signal<String> {
            self.inner.language.clone()
        }

        pub fn set_language(&self, value: String) {
            self.inner.language.set(value);
        }

        pub fn application_name(&self) -> Signal<String> {
            self.inner.application_name.clone()
        }

        pub fn set_application_name(&self, value: String) {
            self.inner.application_name.set(value);
        }

        pub fn organisation_name(&self) -> Signal<String> {
            self.inner.organisation_name.clone()
        }

        pub fn set_organisation_name(&self, value: String) {
            self.inner.organisation_name.set(value);
        }

        pub fn organisation_domain(&self) -> Signal<String> {
            self.inner.organisation_domain.clone()
        }

        pub fn set_organisation_domain(&self, value: String) {
            self.inner.organisation_domain.set(value);
        }

        pub fn prefix_path(&self) -> Signal<String> {
            self.inner.prefix_path.clone()
        }

        pub fn set_prefix_path(&self, value: String) {
            self.inner.prefix_path.set(value);
        }

        pub fn save(&self, _stack_id: Option<u64>) {
            self.inner.dirty.set(false);
        }

        pub fn refresh(&self) {}

        pub fn clear(&self) {
            self.inner.dto.set_if_changed(None);
            self.inner.loading_status.set(LoadingStatus::Unloaded);
        }
    }
}

pub use imp::SingleGlobal;
