// Generated by Qleany v1.12.0 from teksilo_app.tera

//! The demo main window.
//!
//! Regenerating overwrites this file -- it is a `Scaffold`, the starting point
//! you replace with your real UI.

use teksilo::data::{SelectionMode, SelectionModel};
use teksilo::prelude::*;
use teksilo::widgets::{
    Button, ButtonVariant, Checkbox, Divider, Expand, FormLayout, HStack, ListView, Padding, Panel,
    Spacer, StandardListItem, TextInput, TextWidget, VStack,
};

use frontend::EntityId;
use frontend::commands::root_commands;
use frontend::commands::undo_redo_commands;
use frontend::commands::workspace_commands;
use frontend::direct_access::CreateEntityDto;
use frontend::direct_access::CreateRootDto;
use frontend::direct_access::CreateWorkspaceDto;

use crate::models::WorkspaceEntitiesRow;
use crate::session::Session;

/// The entity this window elected to demo.
///
/// Published so the generated headless test (`tests/demo_headless.rs`) can
/// cross-check it against its own election. The election is template-level
/// computation and Tera cannot share a `set_global` across files, so the test
/// template runs its own copy; identical copies drift the moment one is edited,
/// and a drifted test would exercise a list this window never shows -- and pass.
pub const DEMO_ENTITY: &str = "Entity";

/// Create the owner hierarchy the demo window needs, then point the lists at
/// it. Call once, from `run()`.
///
/// A free function here rather than a method on `Session`: this is demo
/// scaffolding, and `app.rs` is the `Scaffold` -- the one file you are meant to
/// throw away. It also keeps the demo-entity election in a single template. The
/// election picks the entity the form and the Add button drive; the hierarchy
/// below is that entity's ownership chain. Elect twice, in two templates, and
/// nothing stops an edit to one from seeding an owner the button never reads,
/// which is a silent no-op button that still compiles.
///
/// The store starts empty. Nothing in the generated UI creates an owner, so
/// without this walk every `*_owner` signal stays `None`, every list model
/// refuses to create under a missing owner, and the demo's
/// "Add Entity" button is a silent no-op.
///
/// **Never from a widget's `build`**: `build` reruns on every rebuild, and a
/// bootstrap that reran would mint a fresh `Root` tree
/// each time. The early return below is a second line of defence, not a
/// licence to move the call.
///
/// The walk is `demo_ent`'s ownership chain, root first:
/// `Root` -> `Workspace` -> `Entity` (yours to add).
pub fn bootstrap(session: &Session) {
    // Scaffolding, not user work: a second call would mint a second
    // `Root` and orphan everything already on screen.
    if session.workspace_entities_owner.get().is_some() {
        log::debug!("bootstrap: already done, skipping");
        return;
    }

    let now = chrono::Utc::now();
    let root_id = match root_commands::create_orphan_root(
        &session.app_ctx,
        // `..Default::default()` covers whatever else this entity carries;
        // the two timestamps are mandatory on every entity and are the one
        // pair a `Default` would leave at the epoch.
        &CreateRootDto {
            created_at: now,
            updated_at: now,
            ..Default::default()
        },
    ) {
        Ok(dto) => dto.id,
        Err(e) => {
            log::error!("bootstrap: could not create the top-level Root: {e}");
            return;
        }
    };
    log::info!("bootstrap: created Root #{root_id}");
    let workspace_id = match workspace_commands::create_workspace(
        &session.app_ctx,
        session.stack_id,
        &CreateWorkspaceDto {
            created_at: now,
            updated_at: now,
            ..Default::default()
        },
        root_id,
        0,
    ) {
        Ok(dto) => dto.id,
        Err(e) => {
            log::error!(
                "bootstrap: could not create a Workspace under Root \
                 #{root_id}: {e}"
            );
            return;
        }
    };
    log::info!("bootstrap: created Workspace #{workspace_id}");

    // Point every list whose owner the walk just created at that owner. A
    // list owned by something the walk does NOT create stays `None` on
    // purpose -- it is waiting for a selection, not broken.
    session.workspace_entities_owner.set(Some(workspace_id));
    session.workspace_features_owner.set(Some(workspace_id));
    // `system_files` hangs off a `System`, which this walk
    // does not create: seed it when one is selected or created.
    // `entity_fields` hangs off a `Entity`, which this walk
    // does not create: seed it when one is selected or created.
    // `feature_use_cases` hangs off a `Feature`, which this walk
    // does not create: seed it when one is selected or created.
    // `use_case_entities` hangs off a `UseCase`, which this walk
    // does not create: seed it when one is selected or created.
    // `dto_fields` hangs off a `Dto`, which this walk
    // does not create: seed it when one is selected or created.

    // The hierarchy above is scenery, not something the user did. Leaving it
    // on the stack would open the app with Undo enabled and one click away
    // from deleting the Workspace the list hangs off.
    // `UndoRedoBinder::wire` re-reads the manager on the first build, so this
    // is visible before anything is drawn.
    undo_redo_commands::clear_all_stacks(&session.app_ctx);
}

/// Two-way form state: one signal per editable scalar of `Entity`.
///
/// `pub`, with `pub` fields, so the generated headless test
/// (`tests/demo_headless.rs`) can fill the form and call [`FormState::to_create_dto`]
/// rather than reimplement it. A copy of this conversion in the test would keep
/// passing while the real one regressed -- which is exactly how a required
/// reference left at id 0 reached a user's second click.
#[derive(Clone)]
pub struct FormState {
    pub name: Signal<String>,
    pub only_for_heritage: Signal<bool>,
    pub single_model: Signal<bool>,
    pub undoable: Signal<bool>,
}

/// `new()` is public so the generated headless test can drive the window's own
/// form rather than a copy of it, and a public argument-less `new` without a
/// `Default` is `clippy::new_without_default`.
impl Default for FormState {
    fn default() -> Self {
        Self::new()
    }
}

impl FormState {
    pub fn new() -> Self {
        Self {
            name: Signal::new(Default::default()),
            only_for_heritage: Signal::new(Default::default()),
            single_model: Signal::new(Default::default()),
            undoable: Signal::new(Default::default()),
        }
    }

    /// Read the widgets back into a Create DTO.
    ///
    /// `..Default::default()` covers every field the form does not own --
    /// relationship ids, lists, optionals -- which is what lets this compile for
    /// an arbitrary entity. The timestamps are stamped by the list model's
    /// `create`, not here.
    pub fn to_create_dto(&self) -> Option<CreateEntityDto> {
        Some(CreateEntityDto {
            name: self.name.get(),
            only_for_heritage: self.only_for_heritage.get(),
            single_model: self.single_model.get(),
            undoable: self.undoable.get(),
            ..Default::default()
        })
    }

    fn clear(&self) {
        self.name.set(Default::default());
        self.only_for_heritage.set(Default::default());
        self.single_model.set(Default::default());
        self.undoable.set(Default::default());
    }
}

pub struct AppRoot {
    session: Session,
    form: FormState,
    selection: SelectionModel,
    selected_id: Signal<Option<EntityId>>,
    root_child: Option<WidgetId>,
}

impl std::fmt::Debug for AppRoot {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AppRoot").finish_non_exhaustive()
    }
}

impl AppRoot {
    pub fn new(session: Session) -> Self {
        Self {
            session,
            form: FormState::new(),
            selection: SelectionModel::new(SelectionMode::Single),
            selected_id: Signal::new(None),
            root_child: None,
        }
    }
}

impl Widget for AppRoot {
    fn build(&mut self, ctx: &mut BuildContext) -> Vec<WidgetId> {
        // Every subscription in the app, reinstalled on every build.
        self.session.wire_all(ctx);

        let stack_id = self.session.stack_id;
        let can_undo = self.session.undo_redo.can_undo();
        let can_redo = self.session.undo_redo.can_redo();

        let header = HStack::new()
            .spacing(12.0)
            .child(TextWidget::new(lit!("Teksilo + Qleany")).style(TextStyleRole::BodyBold))
            .child(TextWidget::new(lit!("Qleany")).color(TextRole::Secondary))
            .child(Spacer::new())
            .child({
                let undo_redo = self.session.undo_redo.clone();
                Button::new(lit!("Undo"))
                    .enabled(can_undo)
                    .on_activate_fn(move |_| undo_redo.undo())
            })
            .child({
                let undo_redo = self.session.undo_redo.clone();
                Button::new(lit!("Redo"))
                    .enabled(can_redo)
                    .on_activate_fn(move |_| undo_redo.redo())
            });

        // ── Column 1: the form ────────────────────────────────────────────
        let mut form = FormLayout::new().row_spacing(8.0);
        form = form.line(
            TextWidget::new(lit!("Name")),
            TextInput::new(self.form.name.clone()).placeholder(lit!("Enter name...")),
        );
        form = form.line(
            TextWidget::new(lit!("OnlyForHeritage")),
            Checkbox::new(self.form.only_for_heritage.clone()).labelled_externally(),
        );
        form = form.line(
            TextWidget::new(lit!("SingleModel")),
            Checkbox::new(self.form.single_model.clone()).labelled_externally(),
        );
        form = form.line(
            TextWidget::new(lit!("Undoable")),
            Checkbox::new(self.form.undoable.clone()).labelled_externally(),
        );

        let add_button = {
            let model = self.session.workspace_entities.clone();
            let form_state = self.form.clone();
            Button::new(lit!("Add Entity"))
                .variant(ButtonVariant::Filled)
                .on_activate_fn(move |_| {
                    let Some(dto) = form_state.to_create_dto() else {
                        return;
                    };
                    // `-1` appends: the order is the user's, and a new row
                    // joining at the top would claim to be first.
                    match model.create(&dto, -1, stack_id) {
                        Some(_) => form_state.clear(),
                        // Keep the form filled -- the user's typing is the only
                        // copy of it -- but never fail silently. The model logs
                        // a backend error itself; the case it cannot see is an
                        // unset owner, which means `bootstrap` did not run or
                        // gave up.
                        None => log::error!(
                            "Add Entity: nothing was created. Either the \
                             backend refused it (logged just above) or \
                             `workspace_entities_owner` is \
                             still None, which means the Workspace bootstrap \
                             did not run."
                        ),
                    }
                })
        };

        let form_column = VStack::new()
            .spacing(8.0)
            .child(TextWidget::new(lit!("New Entity")).style(TextStyleRole::BodyBold))
            .child(Divider::horizontal())
            .child(form)
            .child(add_button)
            .child(Spacer::new());

        // ── Column 2: the list ────────────────────────────────────────────
        let list_model = self.session.workspace_entities.list_model();
        {
            // Selection -> detail, through an effect so it fires only on change:
            // writing during `build` would dirty this widget and rebuild forever.
            let selection = self.selection.selection_signal();
            let rows = list_model.clone();
            let selected_id = self.selected_id.clone();
            let single = self.session.single_entity.clone();
            ctx.effect(&selection, move |indices| {
                let id = indices
                    .iter()
                    .next()
                    .and_then(|i| rows.with_item(*i, |r| r.id));
                selected_id.set_if_changed(id);
                single.set_id(id);
            });
        }

        let list_view = ListView::new(
            list_model,
            move |_index, row: &WorkspaceEntitiesRow, selected| {
                Box::new(
                    StandardListItem::new(lit!(row.display_text()))
                        .subtitle(lit!(format!("#{}", row.id)))
                        .selected(selected),
                )
            },
        )
        .item_height(44.0)
        .selection(self.selection.clone());

        let list_column = VStack::new()
            .spacing(8.0)
            .child(
                TextWidget::new(lit!("Entity list (from Workspace.entities)"))
                    .style(TextStyleRole::BodyBold),
            )
            .child(Divider::horizontal())
            .child(Expand::new().child(list_view));

        // ── Column 3: the detail ──────────────────────────────────────────
        let single = self.session.single_entity.clone();
        // Every value below is *bound* to one of the single's signals. None of
        // them is read with `.get()` here, and that is the whole point: Teksilo
        // does not track signal reads made during `build`. A `.get()` in this
        // function yields a value frozen at build time -- `ctx.effect` only
        // installs an observer, it never marks the widget dirty, and there is no
        // `request_rebuild` -- so the detail column would show the first
        // selection for ever. Widgets update through bindings instead:
        // `TextWidget::text` takes a `Prop<String>`, a `Signal<String>` converts
        // into one, and the widget registers it with the binding registry so a
        // change relayouts and repaints the label on its own.
        // `TextWidget::new` takes a constant `LocalizedString`, so the live value
        // arrives through `.text(..)`, which replaces it. Each row is zipped with
        // the selection so it reads blank when nothing is selected: `clear()`
        // resets the single to `Default`, and the Debug of a default is not
        // nothing -- it is `1970-01-01T00:00:00Z`, `0`, `[]` and the first enum
        // variant, which would look like a real row that happens to be empty.
        // Non-String fields go through `{:?}`, the one formatting every generated
        // type has: enums, Vec, Option, Uuid and DateTime all derive Debug. It
        // runs inside the map, not here, so the row stays live instead of
        // capturing one formatted string.
        let mut rows = FormLayout::new().row_spacing(6.0);
        rows = rows.line(
            TextWidget::new(lit!("CreatedAt")).style(TextStyleRole::BodyBold),
            TextWidget::new(lit!("")).text(self.selected_id.zip(&single.created_at()).map(
                |(selected, value)| match selected {
                    None => String::new(),
                    Some(_) => format!("{value:?}"),
                },
            )),
        );
        rows = rows.line(
            TextWidget::new(lit!("UpdatedAt")).style(TextStyleRole::BodyBold),
            TextWidget::new(lit!("")).text(self.selected_id.zip(&single.updated_at()).map(
                |(selected, value)| match selected {
                    None => String::new(),
                    Some(_) => format!("{value:?}"),
                },
            )),
        );
        rows = rows.line(
            TextWidget::new(lit!("Name")).style(TextStyleRole::BodyBold),
            TextWidget::new(lit!("")).text(self.selected_id.zip(&single.name()).map(
                |(selected, value)| match selected {
                    None => String::new(),
                    Some(_) => value.clone(),
                },
            )),
        );
        rows = rows.line(
            TextWidget::new(lit!("OnlyForHeritage")).style(TextStyleRole::BodyBold),
            TextWidget::new(lit!("")).text(self.selected_id.zip(&single.only_for_heritage()).map(
                |(selected, value)| match selected {
                    None => String::new(),
                    Some(_) => format!("{value:?}"),
                },
            )),
        );
        rows = rows.line(
            TextWidget::new(lit!("SingleModel")).style(TextStyleRole::BodyBold),
            TextWidget::new(lit!("")).text(self.selected_id.zip(&single.single_model()).map(
                |(selected, value)| match selected {
                    None => String::new(),
                    Some(_) => format!("{value:?}"),
                },
            )),
        );
        rows = rows.line(
            TextWidget::new(lit!("Undoable")).style(TextStyleRole::BodyBold),
            TextWidget::new(lit!("")).text(self.selected_id.zip(&single.undoable()).map(
                |(selected, value)| match selected {
                    None => String::new(),
                    Some(_) => format!("{value:?}"),
                },
            )),
        );

        // The "nothing selected" state is a bound status line rather than an
        // `if` choosing between two children. Picking a child during `build` has
        // exactly the defect the rows above avoid: the choice is made once and
        // no later selection can revisit it.
        let detail_column = VStack::new()
            .spacing(8.0)
            .child(TextWidget::new(lit!("Entity Detail")).style(TextStyleRole::BodyBold))
            .child(Divider::horizontal())
            .child(
                TextWidget::new(lit!(""))
                    .text(self.selected_id.map(|o| match o {
                        None => "Select an item in the list".to_string(),
                        Some(id) => format!("Selected #{id}"),
                    }))
                    .color(TextRole::Secondary),
            )
            .child(rows)
            .child(Spacer::new());

        let content = HStack::new()
            .spacing(24.0)
            .child(form_column)
            .child(Expand::new().child(list_column))
            .child(Expand::new().child(detail_column));

        let footer =
            TextWidget::new(lit!("Generated by Qleany -- Qleany")).color(TextRole::Secondary);

        let root = ctx.add(
            Panel::new().child(
                Padding::uniform(16.0).child(
                    VStack::new()
                        .spacing(16.0)
                        .child(header)
                        .child(Divider::horizontal())
                        .child(Expand::new().child(content))
                        .child(Divider::horizontal())
                        .child(footer),
                ),
            ),
        );
        self.root_child = Some(root);
        vec![root]
    }

    fn layout_response(&self, proposal: SizeProposal, ctx: &LayoutContext) -> LayoutResponse {
        self.root_child
            .and_then(|id| ctx.child_size(id, proposal))
            .unwrap_or_else(|| proposal.resolve(0.0, 0.0))
            .into()
    }
}
