// Generated by Qleany v1.12.0 from teksilo_models_mod.tera

//! Layer A -- reactive collections over a Qleany relationship.
//!
//! One model per relationship field marked `list_model: true`. Each reads the
//! *owner's* relationship rather than `get_all_*`: the store is shared, so
//! `get_all` would merge every other owner's children into this list, and it
//! returns database-key order rather than the order the user chose.
//!
//! Like the singles, each file carries a real and a mock arm behind two
//! `#[cfg]`-gated `mod imp` blocks with one public surface.

pub mod coalesced_reload;
mod dto_fields_list_model;
mod entity_fields_list_model;
mod feature_use_cases_list_model;
mod system_files_list_model;
mod use_case_entities_list_model;
mod workspace_entities_list_model;
mod workspace_features_list_model;
pub use dto_fields_list_model::{DtoFieldsListModel, DtoFieldsRow};
pub use entity_fields_list_model::{EntityFieldsListModel, EntityFieldsRow};
pub use feature_use_cases_list_model::{FeatureUseCasesListModel, FeatureUseCasesRow};
pub use system_files_list_model::{SystemFilesListModel, SystemFilesRow};
pub use use_case_entities_list_model::{UseCaseEntitiesListModel, UseCaseEntitiesRow};
pub use workspace_entities_list_model::{WorkspaceEntitiesListModel, WorkspaceEntitiesRow};
pub use workspace_features_list_model::{WorkspaceFeaturesListModel, WorkspaceFeaturesRow};
