// Generated by Qleany v1.12.0 from teksilo_session.tera

//! Everything the UI reads the backend through.
//!
//! One `AppContext`, one single per entity that asked for one, one list model
//! per relationship that asked for one, one undo/redo binder. `Clone` is a
//! handle clone: every clone sees the same singles and the same models.

use std::rc::Rc;

use teksilo::prelude::*;

use frontend::AppContext;
use frontend::EntityId;

#[allow(unused_imports)]
use crate::models::*;
#[allow(unused_imports)]
use crate::singles::*;
use crate::undo_redo::UndoRedoBinder;

#[derive(Clone)]
pub struct Session {
    pub app_ctx: Rc<AppContext>,
    /// The stack every generated mutator is handed. `None` is the default
    /// stack; call `undo_redo_commands::create_new_stack` and store the result
    /// here for a per-document stack.
    pub stack_id: Option<u64>,
    pub undo_redo: UndoRedoBinder,
    pub single_entity: SingleEntity,
    pub single_field: SingleField,
    pub single_feature: SingleFeature,
    pub single_use_case: SingleUseCase,
    pub single_dto: SingleDto,
    pub single_dto_field: SingleDtoField,
    pub single_global: SingleGlobal,
    pub single_user_interface: SingleUserInterface,
    pub workspace_entities: WorkspaceEntitiesListModel,
    /// Which `Workspace` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub workspace_entities_owner: Signal<Option<EntityId>>,
    pub workspace_features: WorkspaceFeaturesListModel,
    /// Which `Workspace` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub workspace_features_owner: Signal<Option<EntityId>>,
    pub system_files: SystemFilesListModel,
    /// Which `System` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub system_files_owner: Signal<Option<EntityId>>,
    pub entity_fields: EntityFieldsListModel,
    /// Which `Entity` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub entity_fields_owner: Signal<Option<EntityId>>,
    pub feature_use_cases: FeatureUseCasesListModel,
    /// Which `Feature` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub feature_use_cases_owner: Signal<Option<EntityId>>,
    pub use_case_entities: UseCaseEntitiesListModel,
    /// Which `UseCase` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub use_case_entities_owner: Signal<Option<EntityId>>,
    pub dto_fields: DtoFieldsListModel,
    /// Which `Dto` the list above belongs to. `None` leaves the
    /// list empty; `app::bootstrap` seeds the ones it can.
    pub dto_fields_owner: Signal<Option<EntityId>>,
}

impl Session {
    pub fn new(app_ctx: Rc<AppContext>) -> Self {
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let workspace_entities_owner: Signal<Option<EntityId>> = Signal::new(None);
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let workspace_features_owner: Signal<Option<EntityId>> = Signal::new(None);
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let system_files_owner: Signal<Option<EntityId>> = Signal::new(None);
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let entity_fields_owner: Signal<Option<EntityId>> = Signal::new(None);
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let feature_use_cases_owner: Signal<Option<EntityId>> = Signal::new(None);
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let use_case_entities_owner: Signal<Option<EntityId>> = Signal::new(None);
        // Its own signal, never a shared one: sharing would re-point every list
        // at the same owner.
        let dto_fields_owner: Signal<Option<EntityId>> = Signal::new(None);

        Self {
            undo_redo: UndoRedoBinder::new(app_ctx.clone(), None),
            single_entity: SingleEntity::new(app_ctx.clone()),
            single_field: SingleField::new(app_ctx.clone()),
            single_feature: SingleFeature::new(app_ctx.clone()),
            single_use_case: SingleUseCase::new(app_ctx.clone()),
            single_dto: SingleDto::new(app_ctx.clone()),
            single_dto_field: SingleDtoField::new(app_ctx.clone()),
            single_global: SingleGlobal::new(app_ctx.clone()),
            single_user_interface: SingleUserInterface::new(app_ctx.clone()),
            workspace_entities: WorkspaceEntitiesListModel::new(
                app_ctx.clone(),
                workspace_entities_owner.clone(),
            ),
            workspace_entities_owner,
            workspace_features: WorkspaceFeaturesListModel::new(
                app_ctx.clone(),
                workspace_features_owner.clone(),
            ),
            workspace_features_owner,
            system_files: SystemFilesListModel::new(app_ctx.clone(), system_files_owner.clone()),
            system_files_owner,
            entity_fields: EntityFieldsListModel::new(app_ctx.clone(), entity_fields_owner.clone()),
            entity_fields_owner,
            feature_use_cases: FeatureUseCasesListModel::new(
                app_ctx.clone(),
                feature_use_cases_owner.clone(),
            ),
            feature_use_cases_owner,
            use_case_entities: UseCaseEntitiesListModel::new(
                app_ctx.clone(),
                use_case_entities_owner.clone(),
            ),
            use_case_entities_owner,
            dto_fields: DtoFieldsListModel::new(app_ctx.clone(), dto_fields_owner.clone()),
            dto_fields_owner,
            stack_id: None,
            app_ctx,
        }
    }

    /// Install every subscription.
    ///
    /// Call from a long-lived widget's `build`, **on every build** -- a
    /// `BuildContext` subscription is scoped to one build cycle and dropped on
    /// the next, so anything that wires once goes deaf after the first rebuild.
    pub fn wire_all(&self, ctx: &mut BuildContext) {
        self.undo_redo.wire(ctx);
        self.single_entity.wire(ctx);
        self.single_field.wire(ctx);
        self.single_feature.wire(ctx);
        self.single_use_case.wire(ctx);
        self.single_dto.wire(ctx);
        self.single_dto_field.wire(ctx);
        self.single_global.wire(ctx);
        self.single_user_interface.wire(ctx);
        self.workspace_entities.wire(ctx);
        self.workspace_features.wire(ctx);
        self.system_files.wire(ctx);
        self.entity_fields.wire(ctx);
        self.feature_use_cases.wire(ctx);
        self.use_case_entities.wire(ctx);
        self.dto_fields.wire(ctx);
        let _ = ctx;
    }
}
