// Generated by Qleany v1.12.0 from teksilo_singles_mod.tera

//! Layer A -- reactive single-entity handles (`Single{Entity}`).
//!
//! A *single* holds one entity by id, exposes its scalar fields as two-way
//! `Signal`s alongside `loading_status` / `error_message` / `dirty`,
//! auto-refreshes when that entity's `Updated` event fires, and writes edits
//! back through `save()`.
//!
//! One file per entity, each holding BOTH a real and a mock definition of the
//! same-named type behind two `#[cfg]`-gated `mod imp` blocks with identical
//! public signatures, then `pub use imp::Name` -- so no `#[cfg]` ever leaks into
//! consuming code. Only building both feature modes keeps the two arms in step.
//!
//! Generated for every entity with `single_model: true` in the manifest.
mod single_dto;
mod single_dto_field;
mod single_entity;
mod single_feature;
mod single_field;
mod single_global;
mod single_use_case;
mod single_user_interface;
pub use single_dto::SingleDto;
pub use single_dto_field::SingleDtoField;
pub use single_entity::SingleEntity;
pub use single_feature::SingleFeature;
pub use single_field::SingleField;
pub use single_global::SingleGlobal;
pub use single_use_case::SingleUseCase;
pub use single_user_interface::SingleUserInterface;

/// Loading lifecycle of a single.
///
/// `Loading` and `Error` are only reachable on the real backend path; the
/// `allow` keeps the mocks build -- which stays `Loaded` -- warning-free.
#[allow(dead_code)]
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum LoadingStatus {
    /// No id set, or the entity was removed.
    #[default]
    Unloaded,
    /// A fetch is in flight.
    Loading,
    /// Data is current.
    Loaded,
    /// The last fetch or save failed; see `error_message`.
    Error,
}
