// Generated by Qleany v1.12.0 from teksilo_tests.tera

//! Headless regression test for the generated Teksilo demo window.
//!
//! This crate compiling proves nothing about the demo *working*. Three separate
//! defects shipped through a green `cargo check`: an owner signal that was never
//! seeded (so the Add button was a silent no-op), a required reference left at
//! `Default` (id 0, so the *second* Add failed a one-to-one constraint), and a
//! detail panel that read its values with `.get()` during `build` (Teksilo does
//! not track reads made there, so it froze on the first selection). Each was
//! found by a human clicking. This test drives the same handles the window
//! drives, so none of them can ship again.
//!
//! **No window, no display.** Nothing here builds a `TeksiloApp` or a
//! `BuildContext`. Every generated handle loads synchronously through
//! `frontend`; the subscriptions a `BuildContext` installs only ever *re*-load,
//! and `wire` ends with the same catch-up refresh this test performs by hand. So
//! this runs headless, in CI, on a machine with no X server.
//!
//! Regenerated freely -- it is `Infrastructure`. The demo it exercises lives in
//! `app.rs`, which is `Scaffold`: replace that with your real UI and this test
//! goes with it.

use std::rc::Rc; // Only the real-backend tests below use `Signal`; under `mocks` they are
// compiled out and this import would be dead.
#[cfg(not(feature = "mocks"))]
use teksilo::prelude::*;

use frontend::AppContext;
// `EntityId` names the ids the real-backend tests pass around; under `mocks`
// those tests are compiled out.
#[cfg(not(feature = "mocks"))]
use frontend::EntityId;
use frontend::commands::root_commands;
use frontend::commands::workspace_commands;

use teksilo_ui::app;
// The form is driven only by the real-backend tests: under `mocks` a create
// goes nowhere, so there is nothing to fill in.
#[cfg(not(feature = "mocks"))]
use teksilo_ui::app::FormState;
use teksilo_ui::session::Session;

/// The window and this test elect the demo entity by running the same template
/// code twice, in two files. Identical copies drift the moment one is edited,
/// and a drifted test would exercise a list the window never shows -- and pass.
/// This turns that into a failure.
#[test]
fn the_window_and_this_test_agree_on_the_demo_entity() {
    assert_eq!(
        app::DEMO_ENTITY,
        "Entity",
        "the demo-entity election in teksilo_app.tera and the one in \
         teksilo_tests.tera no longer agree: the window drives `{}` while every \
         test below drives `Entity`. Everything that follows \
         is testing the wrong thing.",
        app::DEMO_ENTITY
    );
}

/// A fresh backend, a fresh session, bootstrapped exactly as `run()` does.
///
/// No `EventHubClient` is started: the hub's channel is unbounded, so publishing
/// with nobody listening neither blocks nor drops anything this test reads. Each
/// `AppContext` owns its own store, so tests do not see each other.
fn booted() -> Session {
    let session = Session::new(Rc::new(AppContext::new()));
    app::bootstrap(&session);
    session
}

#[cfg(not(feature = "mocks"))]
/// Distinct values for the probe field `name`, one per row.
///
/// Distinct on purpose: a binding frozen on the first row, or one reading a
/// handle nobody re-pointed, reports a *stale value* rather than an empty one,
/// and only a comparison against the expected value can tell those apart.
fn probe_value(nth: u32) -> String {
    format!("probe row {nth}")
}

#[cfg(not(feature = "mocks"))]
/// What the detail row for `Name` renders for the nth row --
/// the same formatting `app.rs` binds into that label.
fn probe_text(nth: u32) -> String {
    probe_value(nth)
}

#[cfg(not(feature = "mocks"))]
/// The window's own form, filled the way a user fills it before clicking Add.
fn filled_form(nth: u32) -> FormState {
    let form = FormState::new();
    form.name.set(probe_value(nth));
    form
}

/// One click of Add.
///
/// `FormState::to_create_dto` is the window's own conversion, called here rather
/// than reimplemented: a copy of it in this file would keep passing while the
/// real one regressed.
#[cfg(not(feature = "mocks"))]
fn add_one(session: &Session, nth: u32) -> Option<EntityId> {
    let dto = filled_form(nth)
        .to_create_dto()
        .expect("the form refused to build a DTO");
    session
        .workspace_entities
        .create(&dto, -1, session.stack_id)
}

#[cfg(not(feature = "mocks"))]
/// Add `count` rows, as `count` clicks of Add would.
fn add_rows(session: &Session, count: u32) -> Vec<EntityId> {
    (1..=count)
        .map(|nth| {
            add_one(session, nth).unwrap_or_else(|| panic!("row {nth} could not be created"))
        })
        .collect()
}

/// Bug #1: the store starts empty, no widget creates an owner, and a list model
/// with no owner refuses every create. `bootstrap` is the only thing that seeds
/// one, and it used not to exist.
#[test]
fn bootstrap_seeds_a_real_owner_for_the_demo_list() {
    let session = booted();

    let owner = session.workspace_entities_owner.get().expect(
        "`workspace_entities_owner` is still None after \
             `bootstrap`: the demo list has no Workspace to hang off, so the \
             window's \"Add Entity\" button is a silent no-op.",
    );

    // The check above is also satisfied by a hardcoded literal. Only a round
    // trip through the backend proves the id names a row that exists.
    let row = workspace_commands::get_workspace(&session.app_ctx, &owner)
        .expect("reading the seeded Workspace back failed");
    assert!(
        row.is_some(),
        "`workspace_entities_owner` is Some({owner}) but no \
         Workspace {owner} exists: bootstrap seeded an id it never created."
    );
}

/// Bug #2: three creates, not one.
///
/// A required reference left at `Default` (id 0) lets the *first* create through
/// and fails every later one on the one-to-one constraint. A single-create test
/// passed that bug all the way to a user's first two clicks.
// The real backend is the subject of the three tests below. Under `mocks` the
// singles and models are replaced by a fabricated `mod imp` that serves a fixed
// set of rows, so "the list starts empty" and "the single reports the row I
// just created" are not merely false there -- they are the wrong question. The
// mock arm gets its own assertion instead, further down.
#[cfg(not(feature = "mocks"))]
#[test]
fn the_demo_entity_can_be_added_repeatedly() {
    let session = booted();
    let list = session.workspace_entities.clone();

    assert_eq!(list.len(), 0, "the demo list should start empty");

    for nth in 1..=3u32 {
        let created = add_one(&session, nth);
        assert!(
            created.is_some(),
            "Add #{nth} of 3 created nothing. Either the backend refused it, or \
             `workspace_entities_owner` is unset."
        );
        assert_eq!(
            list.len(),
            nth as usize,
            "the demo list did not grow on Add #{nth} of 3"
        );
    }
}

/// Bug #3, first half: selecting a row must actually load that row.
///
/// `app.rs` reacts to a selection by calling `single.set_id(id)`. A detail panel
/// pointed at a handle nobody re-points -- or at the wrong handle -- still
/// compiles and still renders; it just always shows the same row.
#[cfg(not(feature = "mocks"))]
#[test]
fn selecting_a_row_loads_that_row_into_the_single() {
    let session = booted();
    let ids = add_rows(&session, 2);
    let single = session.single_entity.clone();

    single.set_id(Some(ids[1]));
    assert_eq!(
        single.id(),
        Some(ids[1]),
        "`set_id` did not take: the single still points elsewhere"
    );
    assert_eq!(
        single.name().get(),
        probe_value(2),
        "the single was pointed at the second row but reports another row's \
         `name`"
    );

    // And it follows a *second* selection, which is the half a load-once
    // implementation gets wrong.
    single.set_id(Some(ids[0]));
    assert_eq!(
        single.name().get(),
        probe_value(1),
        "the single kept the first selection after being re-pointed at the \
         other row"
    );
}

/// Bug #3, second half: the binding path the detail panel actually uses.
///
/// Teksilo does not track signal reads made during `build` -- `BuildContext`'s
/// effect installs an observer but never dirties the widget, and there is no
/// `request_rebuild` -- so a `.get()` in `build` freezes at build time. The panel
/// therefore binds `TextWidget::text(Prop<String>)` to `selected_id` zipped with
/// the single's field signal. The expression below is that binding, and the
/// three assertions move each half of the zip independently: a panel that
/// ignored the selection fails the last one, a panel frozen on the first row
/// fails the middle one.
#[cfg(not(feature = "mocks"))]
#[test]
fn the_detail_binding_follows_both_the_selection_and_the_row() {
    let session = booted();
    let ids = add_rows(&session, 2);
    let single = session.single_entity.clone();

    // `AppRoot`'s own signal. Its selection effect writes this *and* calls
    // `single.set_id` with the same id; both halves are reproduced below.
    let selected_id: Signal<Option<EntityId>> = Signal::new(None);
    let bound = selected_id
        .zip(&single.name())
        .map(|(selected, value)| match selected {
            None => String::new(),
            Some(_) => value.clone(),
        });

    assert_eq!(
        bound.get(),
        "",
        "nothing is selected yet, so the detail row must read blank"
    );

    single.set_id(Some(ids[0]));
    selected_id.set(Some(ids[0]));
    assert_eq!(
        bound.get(),
        probe_text(1),
        "the detail row did not pick up the first selection"
    );

    single.set_id(Some(ids[1]));
    selected_id.set(Some(ids[1]));
    assert_eq!(
        bound.get(),
        probe_text(2),
        "the detail row is stuck on the first selection -- this is what a \
         `.get()` during `build` looks like from the outside"
    );

    // Only the selection changes here; the single still holds the second row.
    // A binding that ignored the selection half of the zip -- or one that merely
    // read back the signal it had just been written -- still says row 2.
    selected_id.set(None);
    assert_eq!(
        bound.get(),
        "",
        "the detail row ignored the selection going empty: it is not reading \
         the selection half of the zip at all"
    );
}

/// `bootstrap` is called from `run()`, once. It guards itself anyway, because a
/// second walk would mint a second `Root` tree and orphan
/// everything already on screen.
/// The mock arm's contract: fabricated rows, available with no backend, and the
/// SAME ones every run. A mock that returned nothing would leave every widget
/// built against it looking correct and empty, which is the failure this arm
/// exists to make impossible.
#[cfg(feature = "mocks")]
#[test]
fn the_mock_arm_serves_deterministic_rows() {
    let session = booted();
    let first: Vec<String> = session
        .workspace_entities
        .rows()
        .iter()
        .map(|row| row.display_text())
        .collect();
    assert!(
        !first.is_empty(),
        "the mock list model served no rows; every widget bound to it would render empty"
    );

    let second: Vec<String> = booted()
        .workspace_entities
        .rows()
        .iter()
        .map(|row| row.display_text())
        .collect();
    assert_eq!(
        first, second,
        "the mock rows changed between runs; fixtures must be deterministic or a \
         row silently changes identity between refreshes"
    );
}

#[test]
fn bootstrap_is_idempotent() {
    let session = booted();
    app::bootstrap(&session);

    let roots =
        root_commands::get_all_root(&session.app_ctx).expect("reading the Root rows back failed");
    assert_eq!(
        roots.len(),
        1,
        "`bootstrap` ran twice and left {} Root rows: the second call \
         must return early, or every list on screen ends up hanging off an \
         orphaned tree.",
        roots.len()
    );
}
