// Generated by Qleany v1.12.0 from teksilo_entity_field_list_model.tera

//! Reactive list over `System.files` (OneToMany -> `File`).
//!
//! Read through the **owner's relationship**, never `get_all_file`: the
//! store is shared, so `get_all` would leak every other owner's children into
//! this list, and it returns database-key order rather than the order the user
//! chose.

use frontend::EntityId;
use frontend::common::entities::FileNature;
use frontend::common::entities::FileStatus;

/// One row: the target's id plus each of its scalar fields.
///
/// `PartialEq` powers the divergence check in `refresh_for`; `Clone` is what
/// `ListModel::with_item` hands back.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct SystemFilesRow {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub relative_path: String,
    pub group: String,
    pub template_name: String,
    pub generated_code: Option<String>,
    pub status: FileStatus,
    pub nature: FileNature,
    pub all_features: bool,
    pub all_entities: bool,
    pub all_use_cases: bool,
}

impl SystemFilesRow {
    /// What a `ListView` delegate shows.
    /// Driven by the manifest's `list_model_displayed_field`.
    pub fn display_text(&self) -> String {
        self.name.clone()
    }
}

#[cfg(not(feature = "mocks"))]
mod imp {
    use std::rc::Rc;

    use teksilo::data::ListModel;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::commands::{file_commands, system_commands};
    use frontend::common::direct_access::system::SystemRelationshipField;
    use frontend::common::event::{DirectAccessEntity, EntityEvent, Origin};
    use frontend::direct_access::{CreateFileDto, UpdateFileDto};

    use crate::models::coalesced_reload::reload_on_events;

    use super::SystemFilesRow;

    /// Read one owner's children, in relationship order.
    fn load_rows(ctx: &AppContext, owner_id: Option<EntityId>) -> Vec<SystemFilesRow> {
        let Some(owner_id) = owner_id else {
            return Vec::new();
        };
        let ids = match system_commands::get_system_relationship(
            ctx,
            &owner_id,
            &SystemRelationshipField::Files,
        ) {
            Ok(ids) => ids,
            Err(e) => {
                log::error!("system.files: reading the relationship failed: {e}");
                return Vec::new();
            }
        };
        if ids.is_empty() {
            return Vec::new();
        }
        // `get_*_multi` preserves input order, so relationship order survives.
        file_commands::get_file_multi(ctx, &ids)
            .unwrap_or_default()
            .into_iter()
            .flatten()
            .map(|dto| SystemFilesRow {
                id: dto.id,
                created_at: dto.created_at,
                updated_at: dto.updated_at,
                name: dto.name.clone(),
                relative_path: dto.relative_path.clone(),
                group: dto.group.clone(),
                template_name: dto.template_name.clone(),
                generated_code: dto.generated_code.clone(),
                status: dto.status.clone(),
                nature: dto.nature.clone(),
                all_features: dto.all_features,
                all_entities: dto.all_entities,
                all_use_cases: dto.all_use_cases,
            })
            .collect()
    }

    struct Inner {
        model: ListModel<SystemFilesRow>,
        /// Bumped only when the rows actually changed. See `refresh_for`.
        version: Signal<u64>,
        owner_id: Signal<Option<EntityId>>,
        ctx: Rc<AppContext>,
    }

    #[derive(Clone)]
    pub struct SystemFilesListModel {
        inner: Rc<Inner>,
    }

    #[allow(dead_code)] // full surface; consumers wire up incrementally
    impl SystemFilesListModel {
        pub fn new(ctx: Rc<AppContext>, owner_id: Signal<Option<EntityId>>) -> Self {
            let rows = load_rows(&ctx, owner_id.get());
            Self {
                inner: Rc::new(Inner {
                    model: ListModel::from_vec(rows),
                    version: Signal::new(0),
                    owner_id,
                    ctx,
                }),
            }
        }

        pub fn list_model(&self) -> ListModel<SystemFilesRow> {
            self.inner.model.clone()
        }

        pub fn version_signal(&self) -> Signal<u64> {
            self.inner.version.clone()
        }

        pub fn owner_id_signal(&self) -> Signal<Option<EntityId>> {
            self.inner.owner_id.clone()
        }

        pub fn set_owner_id(&self, id: Option<EntityId>) {
            self.inner.owner_id.set_if_changed(id);
            self.refresh();
        }

        pub fn rows(&self) -> Vec<SystemFilesRow> {
            (0..self.inner.model.len())
                .filter_map(|i| self.inner.model.with_item(i, |r| r.clone()))
                .collect()
        }

        pub fn len(&self) -> usize {
            self.inner.model.len()
        }

        pub fn is_empty(&self) -> bool {
            self.len() == 0
        }

        pub fn row_at(&self, index: usize) -> Option<SystemFilesRow> {
            self.inner.model.with_item(index, |r| r.clone())
        }

        /// Stay live. Call from the consuming widget's `build`, on every build:
        /// a `BuildContext` subscription lasts one build cycle, so a one-shot
        /// guard would leave the model deaf while reporting itself wired.
        ///
        /// Every origin is routed through `reload_on_events`, which reloads once
        /// per frame however many events arrive -- a batched create publishes one
        /// event per row.
        ///
        /// The owner's `Updated` is in the list because `set_relationship` and
        /// `move_relationship` rewrite the junction on the **owner** and publish
        /// an owner event; no child event is published at all.
        pub fn wire(&self, ctx: &mut BuildContext) {
            let me = self.clone();
            reload_on_events(
                ctx,
                [
                    Origin::DirectAccess(DirectAccessEntity::File(EntityEvent::Created)),
                    Origin::DirectAccess(DirectAccessEntity::File(EntityEvent::Updated)),
                    Origin::DirectAccess(DirectAccessEntity::File(EntityEvent::Removed)),
                    Origin::DirectAccess(DirectAccessEntity::System(EntityEvent::Updated)),
                ],
                move || me.refresh(),
            );
            // Catch up for an owner seeded before this model was wired, or
            // re-wired after a rebuild.
            self.refresh();
        }

        pub fn refresh(&self) {
            self.refresh_for(self.inner.owner_id.get());
        }

        fn refresh_for(&self, owner_id: Option<EntityId>) {
            let rows = load_rows(&self.inner.ctx, owner_id);

            // The version bump is conditional, and that is load-bearing. It means
            // "the list changed", never "somebody re-read it". `wire` ends with a
            // catch-up refresh, and a view that follows this model calls `wire`
            // from its own `build` and binds `version` at rebuild level -- so an
            // unconditional bump is a write made by `build` itself: build ->
            // dirty -> rebuild -> build -> bump, forever, at frame rate.
            let changed = self.rows() != rows;

            // Keyed, not `replace_all`: a `Reset` clears a positional selection,
            // while keyed reconciliation keeps the selection and any focused
            // inline editor alive while a sibling row commits.
            self.inner.model.reconcile_by_key(rows, |r| r.id);

            if changed {
                let version = &self.inner.version;
                version.set(version.get().wrapping_add(1));
            }
        }

        /// Create a `File` under this owner. `index` of `-1` appends.
        ///
        /// `created_at` / `updated_at` are stamped here rather than left to the
        /// caller: they are mandatory on every entity, and forgetting them
        /// writes an epoch timestamp that nothing later notices.
        pub fn create(
            &self,
            dto: &CreateFileDto,
            index: i32,
            _stack_id: Option<u64>,
        ) -> Option<EntityId> {
            let owner_id = self.inner.owner_id.get()?;
            let now = chrono::Utc::now();
            let mut dto = dto.clone();
            dto.created_at = now;
            dto.updated_at = now;
            match file_commands::create_file(&self.inner.ctx, &dto, owner_id, index) {
                Ok(created) => {
                    // Refresh now rather than waiting for the event to come back
                    // round through the hub. The event still arrives and refreshes
                    // again -- harmlessly, reconciliation is idempotent -- but the
                    // caller can read the list it just changed in this same tick.
                    self.refresh();
                    Some(created.id)
                }
                Err(e) => {
                    log::error!("system.files: create failed: {e}");
                    None
                }
            }
        }

        /// Write one row back.
        ///
        /// Read-modify-write off the live entity, not off the row: `created_at`
        /// and any uuid are identity and creation metadata that no list consumer
        /// edits, and re-deriving either here would reset it on every edit.
        pub fn update(&self, row: &SystemFilesRow, _stack_id: Option<u64>) {
            let existing = match file_commands::get_file(&self.inner.ctx, &row.id) {
                Ok(Some(entity)) => entity,
                Ok(None) => return,
                Err(e) => {
                    log::error!("system.files: reading {} failed: {e}", row.id);
                    return;
                }
            };
            let dto = UpdateFileDto {
                id: row.id,
                created_at: existing.created_at,
                updated_at: chrono::Utc::now(),
                name: row.name.clone(),
                relative_path: row.relative_path.clone(),
                group: row.group.clone(),
                template_name: row.template_name.clone(),
                generated_code: row.generated_code.clone(),
                status: row.status.clone(),
                nature: row.nature.clone(),
                all_features: row.all_features,
                all_entities: row.all_entities,
                all_use_cases: row.all_use_cases,
            };
            match file_commands::update_file(&self.inner.ctx, &dto) {
                Ok(_) => self.refresh(),
                Err(e) => log::error!("system.files: update failed: {e}"),
            }
        }

        /// Delete the entity. Emitted because this relationship is strong -- the
        /// owner owns its children.
        pub fn remove(&self, id: EntityId, _stack_id: Option<u64>) {
            match file_commands::remove_file(&self.inner.ctx, &id) {
                Ok(()) => self.refresh(),
                Err(e) => log::error!("system.files: removing {id} failed: {e}"),
            }
        }
    }
}

#[cfg(feature = "mocks")]
mod imp {
    use std::cell::RefCell;
    use std::rc::Rc;

    use teksilo::data::ListModel;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::direct_access::CreateFileDto;

    use super::SystemFilesRow;

    /// Deterministic ids, never random: a fresh id per call would make the same
    /// row change identity between refreshes.
    fn mock_rows() -> Vec<SystemFilesRow> {
        (1..=5u64)
            .map(|id| SystemFilesRow {
                id,
                name: format!("Mock File {id}"),
                relative_path: format!("Mock File {id}"),
                group: format!("Mock File {id}"),
                template_name: format!("Mock File {id}"),
                ..Default::default()
            })
            .collect()
    }

    /// Mutable, unlike most fabricated fixtures: a page whose whole content is
    /// the list it edits is untestable by eye against a fixture that refuses
    /// every edit. Writes land in the model and bump `version`, so the view
    /// reacts as it does against the real store -- it simply forgets on restart.
    #[derive(Clone)]
    pub struct SystemFilesListModel {
        model: ListModel<SystemFilesRow>,
        version: Signal<u64>,
        owner_id: Signal<Option<EntityId>>,
        next_id: Rc<RefCell<EntityId>>,
    }

    #[allow(dead_code)] // identical surface to the real arm; some unused here
    impl SystemFilesListModel {
        pub fn new(_ctx: Rc<AppContext>, owner_id: Signal<Option<EntityId>>) -> Self {
            Self {
                model: ListModel::from_vec(mock_rows()),
                version: Signal::new(0),
                owner_id,
                next_id: Rc::new(RefCell::new(100)),
            }
        }

        pub fn list_model(&self) -> ListModel<SystemFilesRow> {
            self.model.clone()
        }

        pub fn version_signal(&self) -> Signal<u64> {
            self.version.clone()
        }

        pub fn owner_id_signal(&self) -> Signal<Option<EntityId>> {
            self.owner_id.clone()
        }

        pub fn set_owner_id(&self, id: Option<EntityId>) {
            self.owner_id.set_if_changed(id);
        }

        pub fn rows(&self) -> Vec<SystemFilesRow> {
            (0..self.model.len())
                .filter_map(|i| self.model.with_item(i, |r| r.clone()))
                .collect()
        }

        pub fn len(&self) -> usize {
            self.model.len()
        }

        pub fn is_empty(&self) -> bool {
            self.len() == 0
        }

        pub fn row_at(&self, index: usize) -> Option<SystemFilesRow> {
            self.model.with_item(index, |r| r.clone())
        }

        /// No-op under mocks: a mocks build registers no event source, and
        /// `subscribe_event` panics without one.
        pub fn wire(&self, _ctx: &mut BuildContext) {}

        pub fn refresh(&self) {}

        pub fn create(
            &self,
            _dto: &CreateFileDto,
            _index: i32,
            _stack_id: Option<u64>,
        ) -> Option<EntityId> {
            let id = {
                let mut next = self.next_id.borrow_mut();
                *next += 1;
                *next
            };
            self.model.push(SystemFilesRow {
                id,
                name: format!("Mock File {id}"),
                relative_path: format!("Mock File {id}"),
                group: format!("Mock File {id}"),
                template_name: format!("Mock File {id}"),
                ..Default::default()
            });
            self.version.set(self.version.get().wrapping_add(1));
            Some(id)
        }

        pub fn update(&self, row: &SystemFilesRow, _stack_id: Option<u64>) {
            let rows: Vec<_> = self
                .rows()
                .into_iter()
                .map(|r| if r.id == row.id { row.clone() } else { r })
                .collect();
            self.model.reconcile_by_key(rows, |r| r.id);
            self.version.set(self.version.get().wrapping_add(1));
        }

        pub fn remove(&self, id: EntityId, _stack_id: Option<u64>) {
            let rows: Vec<_> = self.rows().into_iter().filter(|r| r.id != id).collect();
            self.model.reconcile_by_key(rows, |r| r.id);
            self.version.set(self.version.get().wrapping_add(1));
        }
    }
}

pub use imp::SystemFilesListModel;
