// Generated by Qleany v1.12.0 from teksilo_entity_field_list_model.tera

//! Reactive list over `UseCase.entities` (ManyToMany -> `Entity`).
//!
//! Read through the **owner's relationship**, never `get_all_entity`: the
//! store is shared, so `get_all` would leak every other owner's children into
//! this list, and it returns database-key order rather than the order the user
//! chose.

use frontend::EntityId;

/// One row: the target's id plus each of its scalar fields.
///
/// `PartialEq` powers the divergence check in `refresh_for`; `Clone` is what
/// `ListModel::with_item` hands back.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct UseCaseEntitiesRow {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub only_for_heritage: bool,
    pub single_model: bool,
    pub undoable: bool,
}

impl UseCaseEntitiesRow {
    /// What a `ListView` delegate shows.
    /// Driven by the manifest's `list_model_displayed_field`.
    pub fn display_text(&self) -> String {
        self.name.clone()
    }
}

#[cfg(not(feature = "mocks"))]
mod imp {
    use std::rc::Rc;

    use teksilo::data::ListModel;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::commands::{entity_commands, use_case_commands};
    use frontend::common::direct_access::use_case::UseCaseRelationshipField;
    use frontend::common::event::{DirectAccessEntity, EntityEvent, Origin};

    use crate::models::coalesced_reload::reload_on_events;

    use super::UseCaseEntitiesRow;

    /// Read one owner's children, in relationship order.
    fn load_rows(ctx: &AppContext, owner_id: Option<EntityId>) -> Vec<UseCaseEntitiesRow> {
        let Some(owner_id) = owner_id else {
            return Vec::new();
        };
        let ids = match use_case_commands::get_use_case_relationship(
            ctx,
            &owner_id,
            &UseCaseRelationshipField::Entities,
        ) {
            Ok(ids) => ids,
            Err(e) => {
                log::error!("use_case.entities: reading the relationship failed: {e}");
                return Vec::new();
            }
        };
        if ids.is_empty() {
            return Vec::new();
        }
        // `get_*_multi` preserves input order, so relationship order survives.
        entity_commands::get_entity_multi(ctx, &ids)
            .unwrap_or_default()
            .into_iter()
            .flatten()
            .map(|dto| UseCaseEntitiesRow {
                id: dto.id,
                created_at: dto.created_at,
                updated_at: dto.updated_at,
                name: dto.name.clone(),
                only_for_heritage: dto.only_for_heritage,
                single_model: dto.single_model,
                undoable: dto.undoable,
            })
            .collect()
    }

    struct Inner {
        model: ListModel<UseCaseEntitiesRow>,
        /// Bumped only when the rows actually changed. See `refresh_for`.
        version: Signal<u64>,
        owner_id: Signal<Option<EntityId>>,
        ctx: Rc<AppContext>,
    }

    #[derive(Clone)]
    pub struct UseCaseEntitiesListModel {
        inner: Rc<Inner>,
    }

    #[allow(dead_code)] // full surface; consumers wire up incrementally
    impl UseCaseEntitiesListModel {
        pub fn new(ctx: Rc<AppContext>, owner_id: Signal<Option<EntityId>>) -> Self {
            let rows = load_rows(&ctx, owner_id.get());
            Self {
                inner: Rc::new(Inner {
                    model: ListModel::from_vec(rows),
                    version: Signal::new(0),
                    owner_id,
                    ctx,
                }),
            }
        }

        pub fn list_model(&self) -> ListModel<UseCaseEntitiesRow> {
            self.inner.model.clone()
        }

        pub fn version_signal(&self) -> Signal<u64> {
            self.inner.version.clone()
        }

        pub fn owner_id_signal(&self) -> Signal<Option<EntityId>> {
            self.inner.owner_id.clone()
        }

        pub fn set_owner_id(&self, id: Option<EntityId>) {
            self.inner.owner_id.set_if_changed(id);
            self.refresh();
        }

        pub fn rows(&self) -> Vec<UseCaseEntitiesRow> {
            (0..self.inner.model.len())
                .filter_map(|i| self.inner.model.with_item(i, |r| r.clone()))
                .collect()
        }

        pub fn len(&self) -> usize {
            self.inner.model.len()
        }

        pub fn is_empty(&self) -> bool {
            self.len() == 0
        }

        pub fn row_at(&self, index: usize) -> Option<UseCaseEntitiesRow> {
            self.inner.model.with_item(index, |r| r.clone())
        }

        /// Stay live. Call from the consuming widget's `build`, on every build:
        /// a `BuildContext` subscription lasts one build cycle, so a one-shot
        /// guard would leave the model deaf while reporting itself wired.
        ///
        /// Every origin is routed through `reload_on_events`, which reloads once
        /// per frame however many events arrive -- a batched create publishes one
        /// event per row.
        ///
        /// The owner's `Updated` is in the list because `set_relationship` and
        /// `move_relationship` rewrite the junction on the **owner** and publish
        /// an owner event; no child event is published at all.
        pub fn wire(&self, ctx: &mut BuildContext) {
            let me = self.clone();
            reload_on_events(
                ctx,
                [
                    Origin::DirectAccess(DirectAccessEntity::Entity(EntityEvent::Created)),
                    Origin::DirectAccess(DirectAccessEntity::Entity(EntityEvent::Updated)),
                    Origin::DirectAccess(DirectAccessEntity::Entity(EntityEvent::Removed)),
                    Origin::DirectAccess(DirectAccessEntity::UseCase(EntityEvent::Updated)),
                ],
                move || me.refresh(),
            );
            // Catch up for an owner seeded before this model was wired, or
            // re-wired after a rebuild.
            self.refresh();
        }

        pub fn refresh(&self) {
            self.refresh_for(self.inner.owner_id.get());
        }

        fn refresh_for(&self, owner_id: Option<EntityId>) {
            let rows = load_rows(&self.inner.ctx, owner_id);

            // The version bump is conditional, and that is load-bearing. It means
            // "the list changed", never "somebody re-read it". `wire` ends with a
            // catch-up refresh, and a view that follows this model calls `wire`
            // from its own `build` and binds `version` at rebuild level -- so an
            // unconditional bump is a write made by `build` itself: build ->
            // dirty -> rebuild -> build -> bump, forever, at frame rate.
            let changed = self.rows() != rows;

            // Keyed, not `replace_all`: a `Reset` clears a positional selection,
            // while keyed reconciliation keeps the selection and any focused
            // inline editor alive while a sibling row commits.
            self.inner.model.reconcile_by_key(rows, |r| r.id);

            if changed {
                let version = &self.inner.version;
                version.set(version.get().wrapping_add(1));
            }
        }
    }
}

#[cfg(feature = "mocks")]
mod imp {
    use std::rc::Rc;

    use teksilo::data::ListModel;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;

    use super::UseCaseEntitiesRow;

    /// Deterministic ids, never random: a fresh id per call would make the same
    /// row change identity between refreshes.
    fn mock_rows() -> Vec<UseCaseEntitiesRow> {
        (1..=5u64)
            .map(|id| UseCaseEntitiesRow {
                id,
                name: format!("Mock Entity {id}"),
                ..Default::default()
            })
            .collect()
    }

    /// Mutable, unlike most fabricated fixtures: a page whose whole content is
    /// the list it edits is untestable by eye against a fixture that refuses
    /// every edit. Writes land in the model and bump `version`, so the view
    /// reacts as it does against the real store -- it simply forgets on restart.
    #[derive(Clone)]
    pub struct UseCaseEntitiesListModel {
        model: ListModel<UseCaseEntitiesRow>,
        version: Signal<u64>,
        owner_id: Signal<Option<EntityId>>,
    }

    #[allow(dead_code)] // identical surface to the real arm; some unused here
    impl UseCaseEntitiesListModel {
        pub fn new(_ctx: Rc<AppContext>, owner_id: Signal<Option<EntityId>>) -> Self {
            Self {
                model: ListModel::from_vec(mock_rows()),
                version: Signal::new(0),
                owner_id,
            }
        }

        pub fn list_model(&self) -> ListModel<UseCaseEntitiesRow> {
            self.model.clone()
        }

        pub fn version_signal(&self) -> Signal<u64> {
            self.version.clone()
        }

        pub fn owner_id_signal(&self) -> Signal<Option<EntityId>> {
            self.owner_id.clone()
        }

        pub fn set_owner_id(&self, id: Option<EntityId>) {
            self.owner_id.set_if_changed(id);
        }

        pub fn rows(&self) -> Vec<UseCaseEntitiesRow> {
            (0..self.model.len())
                .filter_map(|i| self.model.with_item(i, |r| r.clone()))
                .collect()
        }

        pub fn len(&self) -> usize {
            self.model.len()
        }

        pub fn is_empty(&self) -> bool {
            self.len() == 0
        }

        pub fn row_at(&self, index: usize) -> Option<UseCaseEntitiesRow> {
            self.model.with_item(index, |r| r.clone())
        }

        /// No-op under mocks: a mocks build registers no event source, and
        /// `subscribe_event` panics without one.
        pub fn wire(&self, _ctx: &mut BuildContext) {}

        pub fn refresh(&self) {}
    }
}

pub use imp::UseCaseEntitiesListModel;
