// Generated by Qleany v1.12.0 from teksilo_entity_field_list_model.tera

//! Reactive list over `Workspace.entities` (OrderedOneToMany -> `Entity`).
//!
//! Read through the **owner's relationship**, never `get_all_entity`: the
//! store is shared, so `get_all` would leak every other owner's children into
//! this list, and it returns database-key order rather than the order the user
//! chose.

use frontend::EntityId;

/// One row: the target's id plus each of its scalar fields.
///
/// `PartialEq` powers the divergence check in `refresh_for`; `Clone` is what
/// `ListModel::with_item` hands back.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct WorkspaceEntitiesRow {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub only_for_heritage: bool,
    pub single_model: bool,
    pub undoable: bool,
}

impl WorkspaceEntitiesRow {
    /// What a `ListView` delegate shows.
    /// Driven by the manifest's `list_model_displayed_field`.
    pub fn display_text(&self) -> String {
        self.name.clone()
    }
}

#[cfg(not(feature = "mocks"))]
mod imp {
    use std::rc::Rc;

    use teksilo::data::ListModel;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::commands::{entity_commands, workspace_commands};
    use frontend::common::direct_access::workspace::WorkspaceRelationshipField;
    use frontend::common::event::{DirectAccessEntity, EntityEvent, Origin};
    use frontend::direct_access::{CreateEntityDto, UpdateEntityDto};

    use crate::models::coalesced_reload::reload_on_events;

    use super::WorkspaceEntitiesRow;

    /// Read one owner's children, in relationship order.
    fn load_rows(ctx: &AppContext, owner_id: Option<EntityId>) -> Vec<WorkspaceEntitiesRow> {
        let Some(owner_id) = owner_id else {
            return Vec::new();
        };
        let ids = match workspace_commands::get_workspace_relationship(
            ctx,
            &owner_id,
            &WorkspaceRelationshipField::Entities,
        ) {
            Ok(ids) => ids,
            Err(e) => {
                log::error!("workspace.entities: reading the relationship failed: {e}");
                return Vec::new();
            }
        };
        if ids.is_empty() {
            return Vec::new();
        }
        // `get_*_multi` preserves input order, so relationship order survives.
        entity_commands::get_entity_multi(ctx, &ids)
            .unwrap_or_default()
            .into_iter()
            .flatten()
            .map(|dto| WorkspaceEntitiesRow {
                id: dto.id,
                created_at: dto.created_at,
                updated_at: dto.updated_at,
                name: dto.name.clone(),
                only_for_heritage: dto.only_for_heritage,
                single_model: dto.single_model,
                undoable: dto.undoable,
            })
            .collect()
    }

    struct Inner {
        model: ListModel<WorkspaceEntitiesRow>,
        /// Bumped only when the rows actually changed. See `refresh_for`.
        version: Signal<u64>,
        owner_id: Signal<Option<EntityId>>,
        ctx: Rc<AppContext>,
    }

    #[derive(Clone)]
    pub struct WorkspaceEntitiesListModel {
        inner: Rc<Inner>,
    }

    #[allow(dead_code)] // full surface; consumers wire up incrementally
    impl WorkspaceEntitiesListModel {
        pub fn new(ctx: Rc<AppContext>, owner_id: Signal<Option<EntityId>>) -> Self {
            let rows = load_rows(&ctx, owner_id.get());
            Self {
                inner: Rc::new(Inner {
                    model: ListModel::from_vec(rows),
                    version: Signal::new(0),
                    owner_id,
                    ctx,
                }),
            }
        }

        pub fn list_model(&self) -> ListModel<WorkspaceEntitiesRow> {
            self.inner.model.clone()
        }

        pub fn version_signal(&self) -> Signal<u64> {
            self.inner.version.clone()
        }

        pub fn owner_id_signal(&self) -> Signal<Option<EntityId>> {
            self.inner.owner_id.clone()
        }

        pub fn set_owner_id(&self, id: Option<EntityId>) {
            self.inner.owner_id.set_if_changed(id);
            self.refresh();
        }

        pub fn rows(&self) -> Vec<WorkspaceEntitiesRow> {
            (0..self.inner.model.len())
                .filter_map(|i| self.inner.model.with_item(i, |r| r.clone()))
                .collect()
        }

        pub fn len(&self) -> usize {
            self.inner.model.len()
        }

        pub fn is_empty(&self) -> bool {
            self.len() == 0
        }

        pub fn row_at(&self, index: usize) -> Option<WorkspaceEntitiesRow> {
            self.inner.model.with_item(index, |r| r.clone())
        }

        /// Stay live. Call from the consuming widget's `build`, on every build:
        /// a `BuildContext` subscription lasts one build cycle, so a one-shot
        /// guard would leave the model deaf while reporting itself wired.
        ///
        /// Every origin is routed through `reload_on_events`, which reloads once
        /// per frame however many events arrive -- a batched create publishes one
        /// event per row.
        ///
        /// The owner's `Updated` is in the list because `set_relationship` and
        /// `move_relationship` rewrite the junction on the **owner** and publish
        /// an owner event; no child event is published at all.
        pub fn wire(&self, ctx: &mut BuildContext) {
            let me = self.clone();
            reload_on_events(
                ctx,
                [
                    Origin::DirectAccess(DirectAccessEntity::Entity(EntityEvent::Created)),
                    Origin::DirectAccess(DirectAccessEntity::Entity(EntityEvent::Updated)),
                    Origin::DirectAccess(DirectAccessEntity::Entity(EntityEvent::Removed)),
                    Origin::DirectAccess(DirectAccessEntity::Workspace(EntityEvent::Updated)),
                ],
                move || me.refresh(),
            );
            // Catch up for an owner seeded before this model was wired, or
            // re-wired after a rebuild.
            self.refresh();
        }

        pub fn refresh(&self) {
            self.refresh_for(self.inner.owner_id.get());
        }

        fn refresh_for(&self, owner_id: Option<EntityId>) {
            let rows = load_rows(&self.inner.ctx, owner_id);

            // The version bump is conditional, and that is load-bearing. It means
            // "the list changed", never "somebody re-read it". `wire` ends with a
            // catch-up refresh, and a view that follows this model calls `wire`
            // from its own `build` and binds `version` at rebuild level -- so an
            // unconditional bump is a write made by `build` itself: build ->
            // dirty -> rebuild -> build -> bump, forever, at frame rate.
            let changed = self.rows() != rows;

            // Keyed, not `replace_all`: a `Reset` clears a positional selection,
            // while keyed reconciliation keeps the selection and any focused
            // inline editor alive while a sibling row commits.
            self.inner.model.reconcile_by_key(rows, |r| r.id);

            if changed {
                let version = &self.inner.version;
                version.set(version.get().wrapping_add(1));
            }
        }

        /// Create a `Entity` under this owner. `index` of `-1` appends.
        ///
        /// `created_at` / `updated_at` are stamped here rather than left to the
        /// caller: they are mandatory on every entity, and forgetting them
        /// writes an epoch timestamp that nothing later notices.
        pub fn create(
            &self,
            dto: &CreateEntityDto,
            index: i32,
            stack_id: Option<u64>,
        ) -> Option<EntityId> {
            let owner_id = self.inner.owner_id.get()?;
            let now = chrono::Utc::now();
            let mut dto = dto.clone();
            dto.created_at = now;
            dto.updated_at = now;
            match entity_commands::create_entity(&self.inner.ctx, stack_id, &dto, owner_id, index) {
                Ok(created) => {
                    // Refresh now rather than waiting for the event to come back
                    // round through the hub. The event still arrives and refreshes
                    // again -- harmlessly, reconciliation is idempotent -- but the
                    // caller can read the list it just changed in this same tick.
                    self.refresh();
                    Some(created.id)
                }
                Err(e) => {
                    log::error!("workspace.entities: create failed: {e}");
                    None
                }
            }
        }

        /// Write one row back.
        ///
        /// Read-modify-write off the live entity, not off the row: `created_at`
        /// and any uuid are identity and creation metadata that no list consumer
        /// edits, and re-deriving either here would reset it on every edit.
        pub fn update(&self, row: &WorkspaceEntitiesRow, stack_id: Option<u64>) {
            let existing = match entity_commands::get_entity(&self.inner.ctx, &row.id) {
                Ok(Some(entity)) => entity,
                Ok(None) => return,
                Err(e) => {
                    log::error!("workspace.entities: reading {} failed: {e}", row.id);
                    return;
                }
            };
            let dto = UpdateEntityDto {
                id: row.id,
                created_at: existing.created_at,
                updated_at: chrono::Utc::now(),
                name: row.name.clone(),
                only_for_heritage: row.only_for_heritage,
                single_model: row.single_model,
                undoable: row.undoable,
            };
            match entity_commands::update_entity(&self.inner.ctx, stack_id, &dto) {
                Ok(_) => self.refresh(),
                Err(e) => log::error!("workspace.entities: update failed: {e}"),
            }
        }

        /// Delete the entity. Emitted because this relationship is strong -- the
        /// owner owns its children.
        pub fn remove(&self, id: EntityId, stack_id: Option<u64>) {
            match entity_commands::remove_entity(&self.inner.ctx, stack_id, &id) {
                Ok(()) => self.refresh(),
                Err(e) => log::error!("workspace.entities: removing {id} failed: {e}"),
            }
        }

        /// Move a row to `new_index` within the relationship.
        ///
        /// This rewrites the junction on the **owner**, not the child, which is
        /// why `wire` listens for the owner's `Updated`: nothing about the child
        /// changes, so no child event is published.
        pub fn move_to(&self, id: EntityId, new_index: i32, stack_id: Option<u64>) {
            let Some(owner_id) = self.inner.owner_id.get() else {
                return;
            };
            match workspace_commands::move_workspace_relationship(
                &self.inner.ctx,
                stack_id,
                &owner_id,
                &WorkspaceRelationshipField::Entities,
                &[id],
                new_index,
            ) {
                Ok(_) => self.refresh(),
                Err(e) => log::error!("workspace.entities: moving {id} failed: {e}"),
            }
        }
    }
}

#[cfg(feature = "mocks")]
mod imp {
    use std::cell::RefCell;
    use std::rc::Rc;

    use teksilo::data::ListModel;
    use teksilo::prelude::*;

    use frontend::AppContext;
    use frontend::EntityId;
    use frontend::direct_access::CreateEntityDto;

    use super::WorkspaceEntitiesRow;

    /// Deterministic ids, never random: a fresh id per call would make the same
    /// row change identity between refreshes.
    fn mock_rows() -> Vec<WorkspaceEntitiesRow> {
        (1..=5u64)
            .map(|id| WorkspaceEntitiesRow {
                id,
                name: format!("Mock Entity {id}"),
                ..Default::default()
            })
            .collect()
    }

    /// Mutable, unlike most fabricated fixtures: a page whose whole content is
    /// the list it edits is untestable by eye against a fixture that refuses
    /// every edit. Writes land in the model and bump `version`, so the view
    /// reacts as it does against the real store -- it simply forgets on restart.
    #[derive(Clone)]
    pub struct WorkspaceEntitiesListModel {
        model: ListModel<WorkspaceEntitiesRow>,
        version: Signal<u64>,
        owner_id: Signal<Option<EntityId>>,
        next_id: Rc<RefCell<EntityId>>,
    }

    #[allow(dead_code)] // identical surface to the real arm; some unused here
    impl WorkspaceEntitiesListModel {
        pub fn new(_ctx: Rc<AppContext>, owner_id: Signal<Option<EntityId>>) -> Self {
            Self {
                model: ListModel::from_vec(mock_rows()),
                version: Signal::new(0),
                owner_id,
                next_id: Rc::new(RefCell::new(100)),
            }
        }

        pub fn list_model(&self) -> ListModel<WorkspaceEntitiesRow> {
            self.model.clone()
        }

        pub fn version_signal(&self) -> Signal<u64> {
            self.version.clone()
        }

        pub fn owner_id_signal(&self) -> Signal<Option<EntityId>> {
            self.owner_id.clone()
        }

        pub fn set_owner_id(&self, id: Option<EntityId>) {
            self.owner_id.set_if_changed(id);
        }

        pub fn rows(&self) -> Vec<WorkspaceEntitiesRow> {
            (0..self.model.len())
                .filter_map(|i| self.model.with_item(i, |r| r.clone()))
                .collect()
        }

        pub fn len(&self) -> usize {
            self.model.len()
        }

        pub fn is_empty(&self) -> bool {
            self.len() == 0
        }

        pub fn row_at(&self, index: usize) -> Option<WorkspaceEntitiesRow> {
            self.model.with_item(index, |r| r.clone())
        }

        /// No-op under mocks: a mocks build registers no event source, and
        /// `subscribe_event` panics without one.
        pub fn wire(&self, _ctx: &mut BuildContext) {}

        pub fn refresh(&self) {}

        pub fn create(
            &self,
            _dto: &CreateEntityDto,
            _index: i32,
            _stack_id: Option<u64>,
        ) -> Option<EntityId> {
            let id = {
                let mut next = self.next_id.borrow_mut();
                *next += 1;
                *next
            };
            self.model.push(WorkspaceEntitiesRow {
                id,
                name: format!("Mock Entity {id}"),
                ..Default::default()
            });
            self.version.set(self.version.get().wrapping_add(1));
            Some(id)
        }

        pub fn update(&self, row: &WorkspaceEntitiesRow, _stack_id: Option<u64>) {
            let rows: Vec<_> = self
                .rows()
                .into_iter()
                .map(|r| if r.id == row.id { row.clone() } else { r })
                .collect();
            self.model.reconcile_by_key(rows, |r| r.id);
            self.version.set(self.version.get().wrapping_add(1));
        }

        pub fn remove(&self, id: EntityId, _stack_id: Option<u64>) {
            let rows: Vec<_> = self.rows().into_iter().filter(|r| r.id != id).collect();
            self.model.reconcile_by_key(rows, |r| r.id);
            self.version.set(self.version.get().wrapping_add(1));
        }

        pub fn move_to(&self, id: EntityId, new_index: i32, _stack_id: Option<u64>) {
            let mut rows = self.rows();
            if let Some(from) = rows.iter().position(|r| r.id == id) {
                let row = rows.remove(from);
                let to = (new_index.max(0) as usize).min(rows.len());
                rows.insert(to, row);
                self.model.reconcile_by_key(rows, |r| r.id);
                self.version.set(self.version.get().wrapping_add(1));
            }
        }
    }
}

pub use imp::WorkspaceEntitiesListModel;
