// Generated by Qleany v1.11.0 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GetDiffDto {
    pub file_id: u64,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GetDiffReturnDto {
    pub diff_text: String,
}
