// Generated by Qleany v1.11.0 from feature_controller.tera

use crate::GetDiffDto;
use crate::GetDiffReturnDto;
use crate::units_of_work::fill_status_in_files_uow::FillStatusInFilesUnitOfWorkFactory;
use crate::units_of_work::get_file_diff_uow::GetFileDiffUnitOfWorkFactory;
use crate::use_cases::fill_status_in_files_uc::FillStatusInFilesUseCase;
use crate::use_cases::get_file_diff_uc::GetFileDiffUseCase;
use anyhow::Result;

use common::{database::db_context::DbContext, event::EventHub};
use std::sync::Arc;

pub fn fill_status_in_files(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Result<()> {
    let uow_context = FillStatusInFilesUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = FillStatusInFilesUseCase::new(Box::new(uow_context));
    uc.execute()?;
    Ok(())
}

pub fn get_file_diff(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &GetDiffDto,
) -> Result<GetDiffReturnDto> {
    let uow_context = GetFileDiffUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = GetFileDiffUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    Ok(return_dto)
}
