// Generated by Qleany v1.12.0 from frontend_feature_commands.tera

//! CppQtFileGeneration feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use cpp_qt_file_generation::{
    FillCppQtFilesDto, FillCppQtFilesReturnDto, GenerateCppQtCodeDto, GenerateCppQtCodeReturnDto,
    GenerateCppQtFilesDto, GenerateCppQtFilesReturnDto, GenerateCppQtPromptDto,
    GenerateCppQtPromptReturnDto, cpp_qt_file_generation_controller,
};

use common::long_operation::OperationProgress;

pub fn fill_cpp_qt_files(
    ctx: &AppContext,
    dto: &FillCppQtFilesDto,
) -> Result<FillCppQtFilesReturnDto> {
    cpp_qt_file_generation_controller::fill_cpp_qt_files(&ctx.db_context, &ctx.event_hub, dto)
        .context("fill_cpp_qt_files")
}

pub fn generate_cpp_qt_code(
    ctx: &AppContext,
    dto: &GenerateCppQtCodeDto,
) -> Result<GenerateCppQtCodeReturnDto> {
    cpp_qt_file_generation_controller::generate_cpp_qt_code(&ctx.db_context, &ctx.event_hub, dto)
        .context("generate_cpp_qt_code")
}

/// generate_cpp_qt_files (long operation)
pub fn generate_cpp_qt_files(ctx: &AppContext, dto: &GenerateCppQtFilesDto) -> Result<String> {
    cpp_qt_file_generation_controller::generate_cpp_qt_files(
        &ctx.db_context,
        &ctx.event_hub,
        &mut common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        dto,
    )
    .context("generate_cpp_qt_files")
}

/// Get the progress of a generate_cpp_qt_files operation
pub fn get_generate_cpp_qt_files_progress(
    ctx: &AppContext,
    operation_id: &str,
) -> Option<OperationProgress> {
    cpp_qt_file_generation_controller::get_generate_cpp_qt_files_progress(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
}

/// Get the result of a generate_cpp_qt_files operation
pub fn get_generate_cpp_qt_files_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<GenerateCppQtFilesReturnDto>> {
    cpp_qt_file_generation_controller::get_generate_cpp_qt_files_result(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
    .context("getting generate_cpp_qt_files result")
}

/// fill_code_in_cpp_qt_files (long operation)
pub fn fill_code_in_cpp_qt_files(ctx: &AppContext) -> Result<String> {
    cpp_qt_file_generation_controller::fill_code_in_cpp_qt_files(
        &ctx.db_context,
        &ctx.event_hub,
        &mut common::long_operation::lock_or_recover(&ctx.long_operation_manager),
    )
    .context("fill_code_in_cpp_qt_files")
}

/// Get the progress of a fill_code_in_cpp_qt_files operation
pub fn get_fill_code_in_cpp_qt_files_progress(
    ctx: &AppContext,
    operation_id: &str,
) -> Option<OperationProgress> {
    cpp_qt_file_generation_controller::get_fill_code_in_cpp_qt_files_progress(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
}

/// Get the result of a fill_code_in_cpp_qt_files operation
pub fn get_fill_code_in_cpp_qt_files_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<()>> {
    cpp_qt_file_generation_controller::get_fill_code_in_cpp_qt_files_result(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
    .context("getting fill_code_in_cpp_qt_files result")
}

pub fn generate_cpp_qt_prompt(
    ctx: &AppContext,
    dto: &GenerateCppQtPromptDto,
) -> Result<GenerateCppQtPromptReturnDto> {
    cpp_qt_file_generation_controller::generate_cpp_qt_prompt(&ctx.db_context, &ctx.event_hub, dto)
        .context("generate_cpp_qt_prompt")
}
