// Generated by Qleany v1.12.0 from frontend_feature_commands.tera

//! FileGenerationSharedSteps feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use file_generation_shared_steps::{
    GetDiffDto, GetDiffReturnDto, file_generation_shared_steps_controller,
};

pub fn fill_status_in_files(ctx: &AppContext) -> Result<()> {
    file_generation_shared_steps_controller::fill_status_in_files(&ctx.db_context, &ctx.event_hub)
        .context("fill_status_in_files")
}

pub fn get_file_diff(ctx: &AppContext, dto: &GetDiffDto) -> Result<GetDiffReturnDto> {
    file_generation_shared_steps_controller::get_file_diff(&ctx.db_context, &ctx.event_hub, dto)
        .context("get_file_diff")
}
