// Generated by Qleany v1.12.0 from frontend_feature_commands.tera

//! HandlingManifest feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use handling_manifest::{
    CheckReturnDto, CreateDto, CreateReturnDto, ExportToMermaidReturnDto, LoadDto, LoadReturnDto,
    SaveDto, handling_manifest_controller,
};

pub fn load(ctx: &AppContext, dto: &LoadDto) -> Result<LoadReturnDto> {
    handling_manifest_controller::load(&ctx.db_context, &ctx.event_hub, dto).context("load")
}

pub fn save(ctx: &AppContext, dto: &SaveDto) -> Result<()> {
    handling_manifest_controller::save(&ctx.db_context, &ctx.event_hub, dto).context("save")
}

pub fn create(ctx: &AppContext, dto: &CreateDto) -> Result<CreateReturnDto> {
    handling_manifest_controller::create(&ctx.db_context, &ctx.event_hub, dto).context("create")
}

pub fn close(ctx: &AppContext) -> Result<()> {
    handling_manifest_controller::close(&ctx.db_context, &ctx.event_hub).context("close")
}

pub fn export_to_mermaid(ctx: &AppContext) -> Result<ExportToMermaidReturnDto> {
    handling_manifest_controller::export_to_mermaid(&ctx.db_context, &ctx.event_hub)
        .context("export_to_mermaid")
}

pub fn check(ctx: &AppContext) -> Result<CheckReturnDto> {
    handling_manifest_controller::check(&ctx.db_context, &ctx.event_hub).context("check")
}
