// Generated by Qleany v1.12.0 from frontend_feature_commands.tera

//! RustFileGeneration feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use rust_file_generation::{
    FillRustFilesDto, FillRustFilesReturnDto, GenerateRustCodeDto, GenerateRustCodeReturnDto,
    GenerateRustFilesDto, GenerateRustFilesReturnDto, GenerateRustPromptDto,
    GenerateRustPromptReturnDto, rust_file_generation_controller,
};

use common::long_operation::OperationProgress;

pub fn fill_rust_files(ctx: &AppContext, dto: &FillRustFilesDto) -> Result<FillRustFilesReturnDto> {
    rust_file_generation_controller::fill_rust_files(&ctx.db_context, &ctx.event_hub, dto)
        .context("fill_rust_files")
}

/// fill_code_in_rust_files (long operation)
pub fn fill_code_in_rust_files(ctx: &AppContext) -> Result<String> {
    rust_file_generation_controller::fill_code_in_rust_files(
        &ctx.db_context,
        &ctx.event_hub,
        &mut common::long_operation::lock_or_recover(&ctx.long_operation_manager),
    )
    .context("fill_code_in_rust_files")
}

/// Get the progress of a fill_code_in_rust_files operation
pub fn get_fill_code_in_rust_files_progress(
    ctx: &AppContext,
    operation_id: &str,
) -> Option<OperationProgress> {
    rust_file_generation_controller::get_fill_code_in_rust_files_progress(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
}

/// Get the result of a fill_code_in_rust_files operation
pub fn get_fill_code_in_rust_files_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<()>> {
    rust_file_generation_controller::get_fill_code_in_rust_files_result(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
    .context("getting fill_code_in_rust_files result")
}

pub fn generate_rust_code(
    ctx: &AppContext,
    dto: &GenerateRustCodeDto,
) -> Result<GenerateRustCodeReturnDto> {
    rust_file_generation_controller::generate_rust_code(&ctx.db_context, &ctx.event_hub, dto)
        .context("generate_rust_code")
}

/// generate_rust_files (long operation)
pub fn generate_rust_files(ctx: &AppContext, dto: &GenerateRustFilesDto) -> Result<String> {
    rust_file_generation_controller::generate_rust_files(
        &ctx.db_context,
        &ctx.event_hub,
        &mut common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        dto,
    )
    .context("generate_rust_files")
}

/// Get the progress of a generate_rust_files operation
pub fn get_generate_rust_files_progress(
    ctx: &AppContext,
    operation_id: &str,
) -> Option<OperationProgress> {
    rust_file_generation_controller::get_generate_rust_files_progress(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
}

/// Get the result of a generate_rust_files operation
pub fn get_generate_rust_files_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<GenerateRustFilesReturnDto>> {
    rust_file_generation_controller::get_generate_rust_files_result(
        &common::long_operation::lock_or_recover(&ctx.long_operation_manager),
        operation_id,
    )
    .context("getting generate_rust_files result")
}

pub fn generate_rust_prompt(
    ctx: &AppContext,
    dto: &GenerateRustPromptDto,
) -> Result<GenerateRustPromptReturnDto> {
    rust_file_generation_controller::generate_rust_prompt(&ctx.db_context, &ctx.event_hub, dto)
        .context("generate_rust_prompt")
}
