#!/usr/bin/env python3
"""Qleany-specific fixtures; transport, discovery and reports come from teksilo_probe.

Keep manifests outside the checkout and preserve the qleany.yaml basename:
Qleany's developer Open action resolves that name relative to the app's cwd.

Run a probe with `python3 scripts/automation_shell.py` on a working desktop.
The default is a freshly built real-backend debug app; QLEANY_BIN overrides it.
TEKSILO_MCP_BIN selects the matching MCP client. QLEANY_SHOT_DIR selects the
screenshot directory; QLEANY_AUTOMATION_SCRATCH selects disposable fixture space.
Reports exit 0 for pass, 1 for setup/tool errors, and 2 for absent behaviour.

scripts/teksilo_probe is generated by `cargo teksilo init` / `probe install`.
Keep Qleany-specific changes here and in automation_*.py, outside that package.
"""

import os
from pathlib import Path
import shutil
import subprocess
import tempfile

from teksilo_probe import ToolError, navigate, resolve, tree

SCRATCH = os.environ.get("QLEANY_AUTOMATION_SCRATCH") or tempfile.gettempdir()


def repo_root():
    """The workspace root, derived from this file rather than from the cwd.

    A probe that hard-codes an absolute path is a demonstration of a bug, not a
    test of one, and deriving from `__file__` keeps probes working from a git
    worktree.
    """
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def repo_path(*parts):
    return os.path.join(repo_root(), *parts)


def app_binary():
    """The debug binary, rebuilt with the real backend before it is handed over.

    Debug on purpose: release has no automation bridge.

    The rebuild is not a convenience. `cargo test -p qleany --features
    mocks` overwrites `target/debug/qleany` with the mocks build, and a
    probe that then drove it would find "Mock Entity 1" in every list, fail in a
    way that reads like a UI regression, and take a while to be recognised for
    what it is. Building here means the binary a probe drives is always the one it
    means to drive, whatever was compiled last. It is a no-op when nothing has
    changed.
    """
    env = os.environ.get("QLEANY_BIN")
    if env:
        return env
    built = subprocess.run(
        ["cargo", "build", "-p", "qleany", "--bin", "qleany"],
        cwd=repo_root(),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
    )
    if built.returncode != 0:
        raise RuntimeError(
            "could not build the app:\n" + built.stderr.decode("utf-8", "replace")
        )
    candidate = str(resolve.app_binary("qleany", project=repo_root()))
    if not os.path.exists(candidate):
        raise RuntimeError(f"cargo built nothing at {candidate}")
    return candidate


def isolated_config(label):
    """A private XDG_CONFIG_HOME, so a probe never reads or writes the real one.

    Returns the environment passed to `launch_and_attach`.
    """
    home = os.path.join(SCRATCH, f"qleany-automation-{label}-{os.getpid()}")
    os.makedirs(os.path.join(home, "config"), exist_ok=True)
    env = dict(os.environ)
    env["XDG_CONFIG_HOME"] = os.path.join(home, "config")
    env["QLEANY_AUTOMATION_HOME"] = home
    return env


def working_copy(src, label):
    """A throwaway copy of a manifest, outside the repo.

    Asserts the copy really did land outside, because a probe that mutates a
    checked-in fixture corrupts it and then still passes.
    """
    dest_dir = os.path.join(SCRATCH, f"qleany-fixture-{label}-{os.getpid()}")
    if Path(dest_dir).resolve().is_relative_to(Path(repo_root()).resolve()):
        raise RuntimeError("the probe scratch directory must be outside the repository")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, os.path.basename(src))
    shutil.copy2(src, dest)
    os.chmod(dest, 0o644)
    return dest


def overlay_nodes(session, role="Dialog"):
    """Qleany's topmost in-tree overlay, including its root, in document order."""
    nodes = tree.nodes(session)
    roots = tree.find_all(nodes, role=role)
    return [roots[-1], *tree.descendants(nodes, roots[-1])] if roots else []



def go_to(session, label, *, settle=True):
    """Select a Qleany rail page, re-finding if manifest events rebuilt the rail."""
    for attempt in range(3):
        node = tree.wait_for_node(
            session, role="Button", label=label, timeout=10,
            pred=lambda n: not n.get("disabled"),
        )
        if node is None:
            raise RuntimeError(f"the {label!r} page never became available")
        try:
            navigate.click(session, node, settle=False)
        except ToolError as exc:
            # NOT_FOUND guarantees this action was not applied. Never retry an
            # ambiguous transport failure or another rejected action.
            if exc.code != "NOT_FOUND" or attempt == 2:
                raise
            session.settle()
            continue
        if settle:
            session.settle()
        return
