// Generated by Qleany v1.11.0 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct FillCppQtFilesDto {
    pub only_list_already_existing: bool,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct FillCppQtFilesReturnDto {
    pub file_ids: Vec<u64>,
    pub file_names: Vec<String>,
    pub file_groups: Vec<String>,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GenerateCppQtCodeDto {
    pub file_id: u64,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GenerateCppQtCodeReturnDto {
    pub generated_code: String,
    pub timestamp: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GenerateCppQtFilesDto {
    pub file_ids: Vec<u64>,
    pub root_path: String,
    pub prefix: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GenerateCppQtFilesReturnDto {
    pub files: Vec<String>,
    pub timestamp: String,
    pub duration: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GenerateCppQtPromptDto {
    pub feature_id: Option<u64>,
    pub use_case_id: Option<u64>,
    pub context: bool,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct GenerateCppQtPromptReturnDto {
    pub prompt_text: String,
}
