#!/usr/bin/env python3
"""Guard: which Teksilo UI files belong to the generator and which belong to us.

Qleany generates part of its own Teksilo UI, so `crates/teksilo_ui` holds two
kinds of file side by side and nothing in the source tree distinguishes them
except the banner comment the generator writes on line 1:

    // Generated by Qleany v1.12.0 from teksilo_session.tera
    # Generated by Qleany v1.12.0 from teksilo_cargo.tera

The version in that banner moves at every release, so this script matches the
prefix and never the whole line.

MACHINE territory is regenerated. Editing one of those files by hand works
until the next `qleany generate`, which overwrites it without asking. A machine
file whose banner has gone missing therefore means either someone has been
editing generated code, or the generator has changed what it emits and the
other rule below is about to start lying.

HAND territory was generated once as a starting point and is now ours. A hand
file that still carries a banner is a trap twice over: the generator will
happily overwrite it, and the Generate screen's default Modified+New filter
pre-ticks every banner-carrying file, so the file is offered up for rewriting
on every single visit, forever.

There is no third category. A file the generator emitted but that we have
adopted is HAND from the moment we adopt it, banner stripped, even if its
contents are still byte-identical to the template output. A rule with a
"generated but ours and not yet edited" bucket is a rule nobody applies
correctly twice.

A path named explicitly below and absent from disk is a failure, not a pass: a
guard that approves of a file that is gone is worse than no guard at all. The
globbed and walked sets are weaker by nature, since a deleted match simply stops
being a match. They are guarded against losing every match, not against losing
one, and that is the honest limit of this check.

Run from anywhere:  python3 tools/check_generated_territory.py
Exit 0 when the split holds, 1 with the full list of violations when it does not.
"""

import sys
from pathlib import Path

# Resolved from this file, not from the working directory, because run_tests.sh
# and the CI job invoke the script from different places.
REPO_ROOT = Path(__file__).resolve().parent.parent

BANNER_PREFIXES = ("// Generated by Qleany ", "# Generated by Qleany ")

# crates/frontend is regenerated wholesale, so it is walked rather than listed.
# A hard-coded list would go stale the first time a feature or an entity is
# added to the manifest.
MACHINE_TREES = [("crates/frontend", (".rs", ".toml"))]

MACHINE_GLOBS = [
    "crates/teksilo_ui/src/singles/single_*.rs",
    "crates/teksilo_ui/src/models/*_list_model.rs",
]

MACHINE_FILES = [
    "crates/teksilo_ui/src/event_source.rs",
    "crates/teksilo_ui/src/undo_redo.rs",
    "crates/teksilo_ui/src/models/coalesced_reload.rs",
    "crates/teksilo_ui/src/singles.rs",
    "crates/teksilo_ui/src/models.rs",
    "crates/teksilo_ui/src/session.rs",
]

HAND_FILES = [
    "Cargo.toml",
    "crates/slint_ui/Cargo.toml",
    "crates/teksilo_ui/Cargo.toml",
    "crates/teksilo_ui/src/lib.rs",
    "crates/teksilo_ui/src/app.rs",
    "crates/teksilo_ui/src/main.rs",
]


def first_line(path):
    """Line 1 without its newline, or "" for an empty file."""
    # `errors="replace"` rather than a clean decode: a file whose first bytes are
    # not UTF-8 is exactly the kind of thing this guard should report by name, and
    # an exception here would abort the run with a traceback and leave every
    # remaining file unchecked.
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        return handle.readline().rstrip("\n")


def has_banner(path):
    return first_line(path).startswith(BANNER_PREFIXES)


def collect_machine_paths(violations):
    """Every path the generator owns, as repo-relative strings, sorted."""
    paths = set(MACHINE_FILES)

    for tree, suffixes in MACHINE_TREES:
        root = REPO_ROOT / tree
        if not root.is_dir():
            violations.append(
                (tree, "listed as a generated tree but is not a directory",
                 "restore the crate, or drop it from MACHINE_TREES."))
            continue
        found = [p for p in root.rglob("*") if p.suffix in suffixes and p.is_file()]
        # An empty walk would pass every rule below by having nothing to check,
        # which is exactly the silence this guard exists to break.
        if not found:
            violations.append(
                (tree, "generated tree holds no %s file" % " or ".join(suffixes),
                 "the crate is empty or the suffix list is wrong."))
        paths.update(str(p.relative_to(REPO_ROOT)) for p in found)

    for pattern in MACHINE_GLOBS:
        found = sorted(REPO_ROOT.glob(pattern))
        if not found:
            violations.append(
                (pattern, "pattern matches nothing",
                 "the files were renamed or removed; fix MACHINE_GLOBS."))
        paths.update(str(p.relative_to(REPO_ROOT)) for p in found)

    return sorted(paths)


def main():
    violations = []
    machine_paths = collect_machine_paths(violations)

    for rel in machine_paths:
        path = REPO_ROOT / rel
        if not path.is_file():
            violations.append(
                (rel, "listed as generated but missing from disk",
                 "restore the file, or drop it from MACHINE_FILES."))
        elif not has_banner(path):
            violations.append(
                (rel, "generated file has lost its banner, line 1 reads: %r" % first_line(path),
                 "regenerate it, or move it to HAND_FILES if it is ours now."))

    for rel in HAND_FILES:
        path = REPO_ROOT / rel
        if not path.is_file():
            violations.append(
                (rel, "listed as hand-written but missing from disk",
                 "restore the file, or drop it from HAND_FILES."))
        elif has_banner(path):
            violations.append(
                (rel, "hand-written file still carries a generated banner",
                 "delete line 1, and the blank line after it."))

    if violations:
        print("Generated territory check FAILED, %d violation(s):" % len(violations))
        for rel, problem, remedy in violations:
            print("  %s" % rel)
            print("      %s" % problem)
            print("      fix: %s" % remedy)
        return 1

    print("Generated territory OK: %d generated files carry the banner, "
          "%d hand-written files do not." % (len(machine_paths), len(HAND_FILES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
