// Generated by Qleany v1.11.0 from feature_dtos.tera

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct LoadDto {
    pub manifest_path: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct LoadReturnDto {
    pub workspace_id: u64,
    pub manifest_path: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SaveDto {
    pub manifest_path: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CreateDto {
    pub manifest_path: String,
    pub language: CreateLanguage,
    pub application_name: String,
    pub organization_name: String,
    pub manifest_template: ManifestTemplate,
    pub options: Vec<String>,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq, Eq)]
pub enum CreateLanguage {
    #[default]
    Rust,
    CppQt,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq, Eq)]
pub enum ManifestTemplate {
    #[default]
    Blank,
    Minimal,
    DocumentEditor,
    DataManagement,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CreateReturnDto {
    pub manifest_path: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ExportToMermaidReturnDto {
    pub mermaid_diagram: String,
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CheckReturnDto {
    pub warnings: Vec<String>,
    pub critical_errors: Vec<String>,
}

// Hand-written: the shape `handling_manifest_controller::get_check_rules` returns
// to the CLI. Not derived from a use-case DTO, so regeneration drops it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CheckRuleDto {
    pub id: String,
    pub severity: String,
    pub description: String,
}
