// Generated by Qleany v1.11.0 from feature_controller.tera

use crate::CheckReturnDto;
use crate::CheckRuleDto;
use crate::CreateDto;
use crate::CreateReturnDto;
use crate::ExportToMermaidReturnDto;
use crate::LoadDto;
use crate::LoadReturnDto;
use crate::SaveDto;
use crate::units_of_work::check_uow::CheckUnitOfWorkFactory;
use crate::units_of_work::close_uow::CloseUnitOfWorkFactory;
use crate::units_of_work::create_uow::CreateUnitOfWorkFactory;
use crate::units_of_work::export_to_mermaid_uow::ExportToMermaidUnitOfWorkFactory;
use crate::units_of_work::load_uow::LoadUnitOfWorkFactory;
use crate::units_of_work::save_uow::SaveUnitOfWorkFactory;
use crate::use_cases::check_uc::CheckUseCase;
use crate::use_cases::close_uc::CloseUseCase;
use crate::use_cases::create_uc::CreateUseCase;
use crate::use_cases::export_to_mermaid_uc::ExportToMermaidUseCase;
use crate::use_cases::load_uc::LoadUseCase;
use crate::use_cases::save_uc::SaveUseCase;
use anyhow::Result;

use common::{database::db_context::DbContext, event::EventHub};
use std::sync::Arc;

pub fn load(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &LoadDto,
) -> Result<LoadReturnDto> {
    let uow_context = LoadUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = LoadUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    Ok(return_dto)
}

pub fn save(db_context: &DbContext, event_hub: &Arc<EventHub>, dto: &SaveDto) -> Result<()> {
    let uow_context = SaveUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = SaveUseCase::new(Box::new(uow_context));
    uc.execute(dto)?;
    Ok(())
}

pub fn create(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
    dto: &CreateDto,
) -> Result<CreateReturnDto> {
    let uow_context = CreateUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CreateUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute(dto)?;
    Ok(return_dto)
}

pub fn close(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Result<()> {
    let uow_context = CloseUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CloseUseCase::new(Box::new(uow_context));
    uc.execute()?;
    Ok(())
}

pub fn export_to_mermaid(
    db_context: &DbContext,
    event_hub: &Arc<EventHub>,
) -> Result<ExportToMermaidReturnDto> {
    let uow_context = ExportToMermaidUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = ExportToMermaidUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute()?;
    Ok(return_dto)
}

pub fn check(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Result<CheckReturnDto> {
    let uow_context = CheckUnitOfWorkFactory::new(db_context, event_hub);
    let mut uc = CheckUseCase::new(Box::new(uow_context));
    let return_dto = uc.execute()?;
    Ok(return_dto)
}

// Hand-written: exposes the check-rule catalogue to `qleany check --rules`. The
// generator emits only use-case entry points, so re-add after regenerating.
pub fn get_check_rules() -> Vec<CheckRuleDto> {
    use crate::use_cases::check_uc::{CRITICAL_RULES, WARNING_RULES};

    CRITICAL_RULES
        .iter()
        .chain(WARNING_RULES.iter())
        .map(|r| CheckRuleDto {
            id: r.id.to_string(),
            severity: r.severity.to_string(),
            description: r.description.to_string(),
        })
        .collect()
}
